### ISSUE TITLE
Missing Title rule needs to check for the presence of a title tag or og:title

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#10]
We should be checking to make sure one of these are present in the head of the website:

`<title>Example Title</title>`
 or 
`<meta property="og:title" content="Example Title" />`

From an accessibility error perspective, we want to check for the output of a title on the front end of the website. It either needs to be in a title tag or of:title tag. It's not the site title, but the specific title of the page or post (which usually included the site title after the page title).

I think we do want to check for the_title being filled in. That is good because it helps with ease of editing on the backend of the website, which I discussed in the help documentation. 

I do think, though, that this check needs to be modified to actually look for a title tag that is present on the front end. Likely this half of the rule would only come into play in Pro when you have full-page scanning available that checks the head also. There could be an instance when a page title is filled in but the theme is not including a title tag in the head, which would be an accessibility error that would be missed by this rule currently.

Here's the article on this one: https://equalizedigital.com/accessibility-checker/missing-title/

**Comment by SteveJonesDev** [comment]
It should first check for the_title and then either the title tag or the meta tag has content. Is that correct?

**Comment by amberhinds** [comment]
Yes, I think that's fine. I think it's possible that the_title could be blank but a meta tag could be present if they filled in the meta title box in Yoast, for example, but left the title blank. I think in that instance we still want to flag an error because it's a useability problem within their website.

**Comment by SteveJonesDev** [comment]
This has been updated and will go out in the next release.
