### ISSUE TITLE
Front End Highlighting the Wrong Element 

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#100]
On https://amberhinds.com/about/ there is an empty link in the footer that goes to Instagram. This is the code being flagged:
`<a href="https://www.instagram.com/aucoeur/" target="_blank"><i class="fab fa-instagram"></i></a>`

When you click "view on page" it highlights the correct item in the footer and also an Instagram link higher up on the page.

<img width="1788" alt="Screen Shot 2023-02-09 at 12 48 15 PM" src="https://user-images.githubusercontent.com/13153456/217908719-eb9e8d15-134e-4d48-a49a-fa2a21fb3196.png">

This is the code snippet that is getting highlighted but should not be:
`<a style="text-decoration: underline;" href="https://www.instagram.com/aucoeur/" target="_blank" rel="noreferrer noopener" aria-label="Instagram (opens in a new tab)">Instagram</a>`

**Comment by SteveJonesDev** [comment]
![Screen Shot 2023-04-07 at 4 25 48 PM](https://user-images.githubusercontent.com/2895788/230674440-9e85ed0c-9db1-49ec-aeec-50dddf979fa9.png)
