### ISSUE TITLE
Front End Highlighting: Tool Tip Cut Off

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#106]
This is in the search box in the sidebar:
<img width="385" alt="Screen Shot 2023-02-15 at 4 35 12 PM" src="https://user-images.githubusercontent.com/13153456/219204131-00587b16-0f24-4717-b029-6255b82d93b4.png">

I don't actually have this on a published page, but if you need a URL I can get you one.

**Comment by amberhinds** [comment]
It's because there is an overflow:hidden on that sidebar which is several containers up from where the error is flagged.  Is there anyway to force it?  Or remove all overflow:hidden from the page?

**Comment by amberhinds** [comment]
I came across the same thing on [enterprise audit client] website. This is an image missing alt, but the button cannot open anything at all. Here are a few screenshots.

<img width="177" alt="Screen Shot 2023-02-24 at 9 11 59 AM" src="https://user-images.githubusercontent.com/13153456/221214701-3f379603-85df-48d6-87b4-19cb6ee91c23.png">

<img width="267" alt="Screen Shot 2023-02-24 at 9 12 07 AM" src="https://user-images.githubusercontent.com/13153456/221214726-14d131ee-92fd-44fd-be5a-0a5b70efc4f0.png">

**Comment by SteveJonesDev** [comment]
This is related to the absolute position discussion here: https://github.com/equalizedigital/accessibility-checker/issues/108

**Comment by SteveJonesDev** [comment]
Change to pop-up.
