### ISSUE TITLE
Front End Highlighting: Tool Tip Styles Impacted by Site Styles

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#107]
This is on the footer of the RWC website:
<img width="557" alt="Screen Shot 2023-02-15 at 5 03 21 PM" src="https://user-images.githubusercontent.com/13153456/219209574-8baa38f5-a5de-41f7-ab5f-fc45e2a42690.png">
 
The icon is adopting the styles for the icons in the footer.
<img width="665" alt="Screen Shot 2023-02-15 at 5 05 54 PM" src="https://user-images.githubusercontent.com/13153456/219210061-89b8efdd-b740-46f3-bce0-2802630ab776.png">

I think we need to define more styles on these to ensure they ignore what is on the website.

**Comment by amberhinds** [comment]
Here's another example from a different website:
<img width="273" alt="Screen Shot 2023-02-24 at 8 58 23 AM" src="https://user-images.githubusercontent.com/13153456/221210844-acb7454d-dc18-4913-9031-c1d06ac7df9c.png">

The font color is being overwritten by theme styles:
<img width="414" alt="Screen Shot 2023-02-24 at 8 58 53 AM" src="https://user-images.githubusercontent.com/13153456/221210949-4912e595-d554-454a-b99f-fa99cebbb2de.png">

I know we don't normally do this, but I wonder if adding !important might be helpful. Or can we ensure that our styles always load last?

**Comment by SteveJonesDev** [comment]
Setting `!important` might help in some instances but resetting the inheritance is probably a better approach `all: unset;`

**Comment by SteveJonesDev** [comment]
https://github.com/equalizedigital/accessibility-checker/commit/423c4f7eb88f72820ade2c181affaf0b841fec2c

**Comment by amberhinds** [comment]
@SteveJonesDev I'm still getting this issue on the RWC site:
<img width="519" alt="Screen Shot 2023-04-10 at 8 41 41 PM" src="https://user-images.githubusercontent.com/13153456/231033652-404b1397-03db-42bc-b1e3-ba87f2d76e23.png">

https://roadwarriorprd.wpengine.com/b-corp/?edac=15832

**Comment by amberhinds** [comment]
I wonder if this would be resolved when you change these to being a click-triggered popup?
