### ISSUE TITLE
Front End Highlighting: Tool Tips Not Accessible When Behind Other Elements

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#108]
In the header of the RWC website, there is a spacer div over the content. This stops the button from being interactive, and the tooltip cannot be reached.
<img width="1787" alt="Screen Shot 2023-02-15 at 5 12 27 PM" src="https://user-images.githubusercontent.com/13153456/219214446-4f90c87c-f23c-4f8f-8a57-017fefa1c0c7.png">

**Comment by SteveJonesDev** [comment]
I think this is a use case for having a disable styles switch. If you run WAVE on the same page there are WAVE buttons that are blocked as well.

**Comment by amberhinds** [comment]
The down side to that is it's really hard for a non-technical person to
understand what the element is when styles are turned off.

Is there any way to set a Z-index or something that just puts it in front
of everything?

**Comment by SteveJonesDev** [comment]
Absolute positioning the button while maintaining focus order is challenging. If there is any wrapping element up the dom tree with a position of relative it will not position correctly. A workaround to this is to place the button outside of all the elements, but this doesn't maintain the tab order.

**Comment by amberhinds** [comment]
Perhaps we release and leave this open for an update. I have a few other [thoughts I posted in Basecamp](https://3.basecamp.com/3579237/buckets/29333825/messages/6025219466).
