### ISSUE TITLE
Front End Highlighting: Video Not Found

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#109]
This is on https://zightprd.wpengine.com/how-i-use-async-as-a-ceo/

Code snippet:
`<video controls src="http://zightprd.wpengine.com/wp-content/uploads/2023/02/How-I-use-CloudApp-as-a-CEO.mp4"></video>`

It's flagging a missing transcript error.

It's a WordPress video block.

<img width="818" alt="Video block in block editor" src="https://user-images.githubusercontent.com/13153456/220499700-be574ca9-469e-4bab-a92f-07c9dcd68c2e.png">

This is the actual code for the video on the page:
`<figure class="wp-block-video"><video controls="" class="perfmatters-lazy entered pmloaded" data-src="https://zightprd.wpengine.com/wp-content/uploads/2023/02/How-I-use-CloudApp-as-a-CEO.mp4" data-ll-status="loaded" src="https://zightprd.wpengine.com/wp-content/uploads/2023/02/How-I-use-CloudApp-as-a-CEO.mp4"></video><noscript><video controls src="http://zightprd.wpengine.com/wp-content/uploads/2023/02/How-I-use-CloudApp-as-a-CEO.mp4"></video></noscript></figure>`

**Comment by SteveJonesDev** [comment]
This is a conflict with Perfmatter's lazy loading.

A filter has been added to disable lazy loading when highlighting elements with AC.

https://github.com/equalizedigital/accessibility-checker/commit/81460bed2f29d6cab7a712262be1be80748de8f7

![Screen Shot 2023-04-07 at 5 06 27 PM](https://user-images.githubusercontent.com/2895788/230679012-9e46617c-5499-4db2-b274-9cd22e6f2d85.png)
