### ISSUE TITLE
Front End Highlighting: Empty Links Not Found

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#112]
These are the issues:
<img width="1462" alt="Screen Shot 2023-02-24 at 8 49 43 AM" src="https://user-images.githubusercontent.com/13153456/221208624-23b2d0bb-d351-4ad8-8d69-54f773d67acd.png">

AC can't find these on the page.

Example code from AC Issue:
`<a href="https://twitter.com"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/></svg> </a>`

Actual code on front end looks the same to me:
`<a href="https://twitter.com">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg>
			</a>`

These are on enterprise audit client's website.

**Comment by SteveJonesDev** [comment]
Can you confirm that the code is actually on the page? In the console, you should be able to see the selector the javascript is using to find the element. I added both of the code snippets to an HTML block and it worked.

`Element selector: A:contains('  ')[href="https://twitter.com"]`

**Comment by amberhinds** [comment]
<img width="1576" alt="Screen Shot 2023-02-24 at 9 04 03 AM" src="https://user-images.githubusercontent.com/13153456/221211913-6cdfda29-292e-401f-91af-95d6c694b8f3.png">

I can Basecamp you the link.

**Comment by amberhinds** [comment]
<img width="1081" alt="Screen Shot 2023-02-24 at 9 05 07 AM" src="https://user-images.githubusercontent.com/13153456/221212150-a17e965f-3ad6-4a15-8adf-e210d0ed9009.png">

**Comment by SteveJonesDev** [comment]
It's probably the whitespace. The spaces in the :contains selector. Marking as a bug.
