### ISSUE TITLE
Front End Highlighting: Doesn't Remove Inlined Styles When Styles are Turned Off

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#113]
On [enterprise audit client] site, items in the nav aren't visible even when the styles are turned off. The div is only shown when the Explore button is clicked even after the styles are turned off. I spoke with the dev team, and they think it might be because there are inline styles that are not being removed.

This needs to be looked at on their develop branch. Also could talk with them in Slack. Collin had some thoughts.

**Comment by SteveJonesDev** [comment]
The script has been updated to remove inline styles. I think this will fix the issue but it's always possible there is custom javascript on the site that is injecting inline styles as well.
