### ISSUE TITLE
excessive issues on a single page

### ISSUE THREAD

**Issue by territutich** [equalizedigital/accessibility-checker#115]
This page lists 1266 Contrast Errors.  When I look at the issue details, it seems like every tag is listed, and the referenced CSS is the same.

URL: https://wiseowlmarketing.com/clients/

Example Snippet 1:
`<!DOCTYPE html> .gform-theme--framework .gfield--type-multiselect .chosen-container-multi,.gform-theme--framework .gfield--type-select .chosen-search input[type=text],.gform-theme--framework .gfield--type-select .chosen-single,.gform-theme--framework .gform-theme-field-control,.gform-theme--framework input[type]:where(:not(.gform-text-input-reset)),.gform-theme--framework select,.gform-theme--framework select[multiple],.gform-theme--framework textarea,.gform-theme--framework.gform-theme.gform_wrapper .button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper .gform-theme-button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper :where(:not(.mce-splitbtn))>button:not([id*=mceu_]):not(.mce-open):where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper button.button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper input:is([type=submit],[type=button],[type=reset]).button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper input:is([type=submit],[type=button],[type=reset]):where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper input[type=submit].button.gform_button:where(:not(.gform-theme-no-framework)){--gform-theme-local-appearance: var(--gform-theme-control-appearance); --gform-theme-local-background-color: var(--gform-theme-control-background-color); --gform-theme-local-block-size: var(--gform-theme-control-size); --gform-theme-local-border-radius: var(--gform-theme-control-border-radius); --gform-theme-local-border-color: var(--gform-theme-control-border-color); --gform-theme-local-border-width: var(--gform-theme-control-border-width); --gform-theme-local-border-style: var(--gform-theme-control-border-style); --gform-theme-local-border-block-start: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-border-block-end: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-border-inline-start: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-border-inline-end: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-box-shadow: var(--gform-theme-control-box-shadow); --gform-theme-local-color: var(--gform-theme-control-color); --gform-theme-local-display: block; --gform-theme-local-font-family: var(--gform-theme-control-font-family); --gform-theme-local-font-size: var(--gform-theme-control-font-size); --gform-theme-local-font-style: var(--gform-theme-control-font-style); --gform-theme-local-font-weight: var(--gform-theme-control-font-weight); --gform-theme-local-inline-size: 100%; --gform-theme-local-letter-spacing: var(--gform-theme-control-letter-spacing); --gform-theme-local-line-height: var(--gform-theme-control-line-height); --gform-theme-local-min-block-size: auto; --gform-theme-local-outline: var(--gform-theme-control-outline); --gform-theme-local-outline-offset: var(--gform-theme-control-outline-offset); --gform-theme-local-padding-inline: var(--gform-theme-control-padding-inline); --gform-theme-local-padding-block: var(--gform-theme-control-padding-block); --gform-theme-local-transition: var(--gform-theme-control-transition); -webkit-border-after: var(--gform-theme-local-border-block-end); -webkit-border-before: var(--gform-theme-local-border-block-start); -webkit-border-end: var(--gform-theme-local-border-inline-end); -webkit-border-start: var(--gform-theme-local-border-inline-start); -webkit-appearance: var(--gform-theme-local-appearance); -moz-appearance: var(--gform-theme-local-appearance); appearance: var(--gform-theme-local-appearance); background-color: --gform-theme-local-background-color; block-size: var(--gform-theme-local-block-size); border-block-end: var(--gform-theme-local-border-block-end); border-block-start: var(--gform-theme-local-border-block-start); border-inline-end: var(--gform-theme-local-border-inline-end); border-inline-start: var(--gform-theme-local-border-inline-start); border-radius: var(--gform-theme-local-border-radius); box-shadow: var(--gform-theme-local-box-shadow); color: var(--gform-theme-local-color); display: var(--gform-theme-local-display); font-family: var(--gform-theme-local-font-family); font-size: --gform-theme-local-font-size; font-style: var(--gform-theme-local-font-style); font-weight: --gform-theme-local-font-weight; inline-size: var(--gform-theme-local-inline-size); letter-spacing: var(--gform-theme-local-letter-spacing); line-height: var(--gform-theme-local-line-height); margin-block: 0; margin-inline: 0; min-block-size: var(--gform-theme-local-min-block-size); outline: var(--gform-theme-local-outline); outline-offset: var(--gform-theme-local-outline-offset); padding-block: var(--gform-theme-local-padding-block); padding-inline: var(--gform-theme-local-padding-inline); transition: var(--gform-theme-local-transition); }`

Example 2:
`<meta name='viewport' content='width=device-width, initial-scale=1.0' /> .gform-theme--framework .gfield--type-multiselect .chosen-container-multi,.gform-theme--framework .gfield--type-select .chosen-search input[type=text],.gform-theme--framework .gfield--type-select .chosen-single,.gform-theme--framework .gform-theme-field-control,.gform-theme--framework input[type]:where(:not(.gform-text-input-reset)),.gform-theme--framework select,.gform-theme--framework select[multiple],.gform-theme--framework textarea,.gform-theme--framework.gform-theme.gform_wrapper .button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper .gform-theme-button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper :where(:not(.mce-splitbtn))>button:not([id*=mceu_]):not(.mce-open):where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper button.button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper input:is([type=submit],[type=button],[type=reset]).button:where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper input:is([type=submit],[type=button],[type=reset]):where(:not(.gform-theme-no-framework)),.gform-theme--framework.gform-theme.gform_wrapper input[type=submit].button.gform_button:where(:not(.gform-theme-no-framework)){--gform-theme-local-appearance: var(--gform-theme-control-appearance); --gform-theme-local-background-color: var(--gform-theme-control-background-color); --gform-theme-local-block-size: var(--gform-theme-control-size); --gform-theme-local-border-radius: var(--gform-theme-control-border-radius); --gform-theme-local-border-color: var(--gform-theme-control-border-color); --gform-theme-local-border-width: var(--gform-theme-control-border-width); --gform-theme-local-border-style: var(--gform-theme-control-border-style); --gform-theme-local-border-block-start: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-border-block-end: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-border-inline-start: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-border-inline-end: var(--gform-theme-local-border-width) var(--gform-theme-local-border-style) var(--gform-theme-local-border-color); --gform-theme-local-box-shadow: var(--gform-theme-control-box-shadow); --gform-theme-local-color: var(--gform-theme-control-color); --gform-theme-local-display: block; --gform-theme-local-font-family: var(--gform-theme-control-font-family); --gform-theme-local-font-size: var(--gform-theme-control-font-size); --gform-theme-local-font-style: var(--gform-theme-control-font-style); --gform-theme-local-font-weight: var(--gform-theme-control-font-weight); --gform-theme-local-inline-size: 100%; --gform-theme-local-letter-spacing: var(--gform-theme-control-letter-spacing); --gform-theme-local-line-height: var(--gform-theme-control-line-height); --gform-theme-local-min-block-size: auto; --gform-theme-local-outline: var(--gform-theme-control-outline); --gform-theme-local-outline-offset: var(--gform-theme-control-outline-offset); --gform-theme-local-padding-inline: var(--gform-theme-control-padding-inline); --gform-theme-local-padding-block: var(--gform-theme-control-padding-block); --gform-theme-local-transition: var(--gform-theme-control-transition); -webkit-border-after: var(--gform-theme-local-border-block-end); -webkit-border-before: var(--gform-theme-local-border-block-start); -webkit-border-end: var(--gform-theme-local-border-inline-end); -webkit-border-start: var(--gform-theme-local-border-inline-start); -webkit-appearance: var(--gform-theme-local-appearance); -moz-appearance: var(--gform-theme-local-appearance); appearance: var(--gform-theme-local-appearance); background-color: --gform-theme-local-background-color; block-size: var(--gform-theme-local-block-size); border-block-end: var(--gform-theme-local-border-block-end); border-block-start: var(--gform-theme-local-border-block-start); border-inline-end: var(--gform-theme-local-border-inline-end); border-inline-start: var(--gform-theme-local-border-inline-start); border-radius: var(--gform-theme-local-border-radius); box-shadow: var(--gform-theme-local-box-shadow); color: var(--gform-theme-local-color); display: var(--gform-theme-local-display); font-family: var(--gform-theme-local-font-family); font-size: --gform-theme-local-font-size; font-style: var(--gform-theme-local-font-style); font-weight: --gform-theme-local-font-weight; inline-size: var(--gform-theme-local-inline-size); letter-spacing: var(--gform-theme-local-letter-spacing); line-height: var(--gform-theme-local-line-height); margin-block: 0; margin-inline: 0; min-block-size: var(--gform-theme-local-min-block-size); outline: var(--gform-theme-local-outline); outline-offset: var(--gform-theme-local-outline-offset); padding-block: var(--gform-theme-local-padding-block); padding-inline: var(--gform-theme-local-padding-inline); transition: var(--gform-theme-local-transition); }`

**Comment by SteveJonesDev** [comment]
A fix for this was released several months ago. Closing this ticket out. If you're still experiencing this issue after updating please reply to this issue.
