### ISSUE TITLE
Prompt for Simplified Summary: add option for 'never'

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#123]
In the Accessibility Checker Settings update the Prompt for Simplified Summary setting with a third option of 'None'.

![Screen Shot 2023-03-01 at 11 38 34 AM](https://user-images.githubusercontent.com/2895788/222204359-4907da7e-6315-4bc7-8e83-9f7b758fc214.png)

Update the Readability tab to include this logic.

![Screen Shot 2023-04-27 at 1 56 27 PM](https://user-images.githubusercontent.com/2895788/234951479-550e2ff2-54b6-4808-b433-9d54c8370562.png)

**Comment by SteveJonesDev** [comment]
@boonedev, here is the first issue. Please submit a pull request to the master branch. Feel free to ask any questions you may have here.

**Comment by boonedev** [comment]
Hi @SteveJonesDev. For this, does the Prompt for Simplified Summary have any bearing on if a summary is shown on the page? For example, if a page reads above an 9th grade level and someone enters a summary for a page but then later changes the Prompt for Simplified Summary to Never, should that summary still be shown on the page?

**Comment by amberhinds** [comment]
I think that the main setting is set to never ask for one, it should
probably override the positioning setting and stop it from outputting.

*Amber Hinds*
Creative Director & CEO
Road Warrior Creative

***@***.*** • (512) 942-5858 <5129425858> ext. 3
*Connect With Me on LinkedIn <http://bit.ly/AmberLinkedIn> *•
https://roadwarriorcreative.com

**Comment by SteveJonesDev** [comment]
@boonedev, the Simplified summary filters the_content and then adds the summary before or after the content. Currently, when outputting the simplified summary it doesn't take the grade level into account. It only checks if the simplified summary exists. If set to 'Never' then it should not output the simplified summary at all.

https://github.com/equalizedigital/accessibility-checker/blob/master/accessibility-checker.php#L1527C54-L1537
