### ISSUE TITLE
Add Naked Link Error

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#126]
We should have an error that tells people not to do this.

<img width="716" alt="example of a naked link on a page" src="https://user-images.githubusercontent.com/13153456/227128384-f490360a-4234-4c19-96d1-992d136b1f3e.png">

@SteveJonesDev - I don't remember how to open an issue with sub-issues so just creating one here, but this will need me to write up documentation in addition to you or other dev coding it.

**Comment by amberhinds** [comment]
@SteveJonesDev @pattonwebz - I corrected above to say that I think we should categorize this as an error.  Here are [examples of pass/fail on our rule testing site.](https://a11ycheckrules.wpenginepowered.com/naked-link/)

**Comment by SteveJonesDev** [comment]
Moved to Basecamp
