### ISSUE TITLE
UAGB Slider not triggering a slider is present warning

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#143]
It uses Swipper, but this isn't triggering the warning.
https://github.com/equalizedigital/accessibility-checker/blob/fe62b9248a9224cbb98a43bbf8feab1a8d56c189/includes/rules/slider_present.php#L27

Here's an example page: https://roadwarriorprd.wpengine.com/wp-admin/post.php?post=9691&action=edit

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
