### ISSUE TITLE
Color Contrast being missed

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#145]
On https://roadwarriorprd.wpengine.com/page-with-lots-of-a11y-problems/ the image captions are very light gray.
<img width="396" alt="Screen Shot 2023-04-10 at 10 00 27 PM" src="https://user-images.githubusercontent.com/13153456/231044915-fea21f6a-e78d-492f-a3f3-41e4bc5645b1.png">

`.wp-block-audio figcaption, .wp-block-embed figcaption, .wp-block-image figcaption {
    color: #dddddd;
    font-size: 16px;
    font-style: italic;
    margin-bottom: 30px;
    margin-top: 10px;
}`

This is not flagging a color contrast error, though I expect it to on a white background.

**Comment by SteveJonesDev** [comment]
Closing this issue as it will be fixed with JavaScript scanning. https://github.com/equalizedigital/accessibility-checker/issues/246
