### ISSUE TITLE
jQuery Migrate Helper plugin logging deprecation warning

### ISSUE THREAD

**Issue by philwp** [equalizedigital/accessibility-checker#15]
The following warning is logged by jQuery Migrate Helper when installing the plugin.
<img width="665" alt="Screen Shot 2021-01-07 at 2 06 44 PM" src="https://user-images.githubusercontent.com/5949352/103933621-acb7d000-50f1-11eb-8c30-97caa3e1eedd.png">

**Comment by SteveJonesDev** [comment]
This has been fixed. I'll do the same for the pro plugin.
