### ISSUE TITLE
Repeated ID attributes on How to Install & Activate Accessibility Checker documentation

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#152]
A customer noticed this.

>  You have repeated id attributes on the https://equalizedigital.com/accessibility-checker/how-to-install-activate-accessibility-checker/ page, making it impossible to link directly to the pro version of the download and install headings.

![Screen Shot 2023-05-23 at 10 29 27 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/7daea01c-5576-4546-ab67-32b9a15efc44)

**Comment by amberhinds** [comment]
Fixed.
