### ISSUE TITLE
Freemius Replacment

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#155]

**Comment by SteveJonesDev** [comment]
Freemius has been removed. A custom opt-in has been added been added to the welcome screen.

**Comment by amberhinds** [comment]
I don't think this can be closed. The email address is being collected, but Freemius was doing a lot more than that - it was gathering data about their install. Would it be better to reopen this with additional information or create a new issue with details about information we want to gather about their install?

**Comment by SteveJonesDev** [comment]
A new descriptive issue is needed.
