### ISSUE TITLE
Front End Highlighting: Change 'Affected Code' button text to 'Show Code'.

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#158]
<img width="424" alt="Screen Shot 2023-06-05 at 10 06 22 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/7224d521-c28d-4a97-8328-9475cca60ab3">

**Comment by boonedev** [comment]
This commit should fix: 9fe7e308a875cf84e6ddc0f2fac12c25b750845e
