### ISSUE TITLE
Front End Highlighting: View on page button needs to focus on the correct element on the frontend

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#160]
<img width="769" alt="Screen Shot 2023-06-06 at 11 04 53 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/532f6172-12c5-4b13-8d27-fa755c2a9a98">

**Comment by boonedev** [comment]
This commit should fix: c9a49734e1d744db66b11ac2cdeb9f898f6ad272

**Comment by SteveJonesDev** [comment]
@boonedev, do you think we should set the scroll position to the current element? I have to scroll up to find the element each time.

**Comment by boonedev** [comment]
@SteveJonesDev commit a4bcad0e641c679da5e3fbca27906bb0bf6845e2 should fix - could you let me know if not?

**Comment by SteveJonesDev** [comment]
@boonedev, I'm not seeing the scroll position moved to the current element.

**Comment by SteveJonesDev** [comment]
This looks to be working now.
