### ISSUE TITLE
Image column needs a max height and width

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#163]
On NASA, they have one SVG that is huge and it explodes out of the column in the in-page reports.
<img width="1316" alt="Screen Shot 2023-06-07 at 6 30 41 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/c4ea0bb2-f591-4de6-8712-f7196c503854">

Can we set a max height and width on these so they can't overflow?

**Comment by amberhinds** [comment]
I encountered this on the WPAD website and it made the button hard to read. In some situations, I think it could potentially make them unusable.

<img width="1322" alt="Screen Shot 2023-08-10 at 6 44 27 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/d92b3baa-fce6-4a28-88c7-ea235d38abee">

**Comment by SteveJonesDev** [comment]
Moved to Basecamp
