### ISSUE TITLE
Consider using content hash for storing & selecting rules

### ISSUE THREAD

**Issue by boonedev** [equalizedigital/accessibility-checker#164]
WPEngine kills SELECT queries where result is > than 16k characters, ie:
https://wpengine.com/support/troubleshoot-wordpress-wp-engine-error-log/#error_KILLED_QUERY

WPEngine's log report:
`KILLED QUERY (101684 characters long generated in /nas/content/live/lhblind/wp-content/plugins/accessibility-checker/includes/insert.php:54): SELECT postid, ignre FROM wp_accessibility_checker where type = 'post' and postid = 16533 and rule = 'color_contrast_failure' and object = '<body data-rss....`

This SELECT can return very large results:
https://github.com/equalizedigital/accessibility-checker/blob/e7db78466a71c5b80b432d637cd929d6752a69d3/includes/insert.php#L44-L55

Temp fix recommended to customers:
>add the following to your wp-config.php between "# WP Engine Settings" and "# That’s It. Pencils down" then save the changes to the file: `define( 'WPE_GOVERNOR', false );`

**Comment by SteveJonesDev** [comment]
Do we know what version of the plugins this user was using?

**Comment by boonedev** [comment]
1.3.28

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
