### ISSUE TITLE
Front-end: What can we do with positioning when issues are very close to one another?

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#168]
<img width="1075" alt="Screen Shot 2023-06-16 at 2 26 47 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/28fd01c1-005f-4e3f-99a7-4c89518b277a">

I can't tell which of these is being focused because the icon being focused and pink outline is smaller than the issue icon.  Can our issue icon be positioned differently relative to what we're flagging?

**Comment by boonedev** [comment]
@amberhinds This commit 4288a3a69f688df37653a6d5dd85fc3143bc3601 adds an outline to the icon for the active issue, so next/previous will cycle on/off the highlight, ie:
<img width="152" alt="Screenshot 2023-06-21 at 5 57 45 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/fa72d470-69cb-4f88-b25a-0a02c7c112bc">
<img width="168" alt="Screenshot 2023-06-21 at 5 57 39 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/915e669b-c58f-48e5-a829-26a7dd9667f8">

**Comment by amberhinds** [comment]
I'm getting the active icon highlighted now, which is helpful, but it's not like I can actually see the element it's flagging:
<img width="296" alt="Screen Shot 2023-06-22 at 1 56 08 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/5f6e178d-fb50-46a0-9e8d-af0c5c51b93a">

This is what it looks like if I run WAVE on that same element:
<img width="381" alt="Screen Shot 2023-06-22 at 1 56 53 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/997a3b4d-d56c-4ea8-aeba-e1199227db04">

Can we do something to position the icons differently?
