### ISSUE TITLE
Should there be a setting to toggle the front end alert on and off?

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#170]
I'm not sure about this always being visible for logged in users:
<img width="93" alt="Screen Shot 2023-06-16 at 2 54 04 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/a3dcec58-385d-4088-a8a5-fcc2871f13e3">

Maybe it's fine, but I do wonder if admins might want to be able to turn it off and decide not to show it.  What do you all think?

**Comment by boonedev** [comment]
I'm for making it always visible (w/o the option to hide) on page preview if there are errors or warnings - b/c otherwise out of sight out of mind. We can always add a hide option later if there is a good use case for needing it.

**Comment by amberhinds** [comment]
I had the same thought.  We can leave it and add that setting later if people ask for it.
