### ISSUE TITLE
Front-end: Inconsistent alerting of issues on button

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#172]
On the RWC site we use for testing, I see 15 issues on the button:
<img width="93" alt="Screen Shot 2023-06-16 at 3 03 48 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/fbda446f-9983-4390-86a2-1d708cb3ec3d">

On my blog, I don't get a count even though there are many issue (30+):
<img width="90" alt="Screen Shot 2023-06-16 at 3 04 30 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/3f7a74a4-94a1-42bc-abf2-b338e9162e44">

**Comment by SteveJonesDev** [comment]
@amberhinds, that is from the Editor11y plugin.

**Comment by amberhinds** [comment]
Hah! I forgot we had that plugin on that site. Explains the count being
lower - it doesn't look for as many things as we do.
