### ISSUE TITLE
Front-end: Insufficienct color contrast on keyboard focus

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#173]
<img width="506" alt="Screen Shot 2023-06-16 at 3 07 00 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/e4526110-9cda-4a30-8ef5-7e164101083a">
<img width="435" alt="Screen Shot 2023-06-16 at 3 07 11 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/83a6e4da-2f5e-4dee-b166-bd2354b0d897">

Chrome, Mac, VoiceOver turned on

**Comment by SteveJonesDev** [comment]
This looks to be fixed now.
