### ISSUE TITLE
Front-end: Image not found on page

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#178]
https://roadwarriorprd.wpengine.com/one-week/

Here's an example of an image it cannot find with front end highlighting.

<img width="1689" alt="Screen Shot 2023-06-22 at 12 33 11 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/765c81da-5bde-4cc3-9af5-0943ab19839b">

**Comment by SteveJonesDev** [comment]
Looks like it might be this rogue space.

![Screen Shot 2023-06-22 at 2 36 22 PM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/813085e4-3ed6-4864-8c09-e089f3f5542c)
