### ISSUE TITLE
Front-end: Image links not found on page

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#179]
https://roadwarriorprd.wpengine.com/one-week/

Here's an example of linked images not being found on the front end:
<img width="1774" alt="Screen Shot 2023-06-22 at 12 37 59 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/976f89f0-6b75-4836-97d8-f8f35b99a134">

**Comment by boonedev** [comment]
@amberhinds I think this PR should fix: https://github.com/equalizedigital/accessibility-checker/pull/199
