### ISSUE TITLE
Front-End: Inconsistent Scrolling

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#181]
See this video: https://watch.screencastify.com/v/WWaRekxOicfXa6HCVNGX

There's an issue or two where it doesn't scroll to it. Anything we can do?  This is on https://roadwarriorprd.wpengine.com/one-week/

**Comment by SteveJonesDev** [comment]
@boonedev, I see that the target button doesn't move with the element now but it still doesn't scroll to the element. Well, technically it does scroll to it as it's absolutely positioned it's just behind everything to achieve the parallax-like effect. Maybe this is an edge case. What are your thoughts?

**Comment by boonedev** [comment]
@SteveJonesDev Yep. I don't know of any way to consistently solve display problems caused by parallax and other fixed positioned stuff. I'd like to treat those as edge case and use the disable styles feature as the recommended way to handle.

**Comment by SteveJonesDev** [comment]
Marking this solved for now. We may revisit it at another time.
