### ISSUE TITLE
Front-end: elements that violate multiple rules

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#183]
This is an interesting one. On https://amberhinds.com/about/

<a href="https://www.facebook.com/aucoeurblog" target="_blank"><i class="fab fa-facebook-f"></i></a> flags two things:

1. Link opens new window or tab
2. Empty link

The first one can be found:
<img width="1158" alt="Screen Shot 2023-06-22 at 1 00 49 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/5155aa72-60c6-416e-b2a6-3e9911dc0849">

The second cannot - though it's the same code:
<img width="1136" alt="Screen Shot 2023-06-22 at 1 01 23 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/a37c06fa-c04b-4cc3-8243-bedf20450afb">

I wonder if we have accounted for elements that violate multiple rules.

**Comment by boonedev** [comment]
[5e47155](https://github.com/equalizedigital/accessibility-checker/commit/90925e62c828b8dbb09d0c941af208a8faf92f59) fixes #183.

Please disregard [8b1887f](https://github.com/equalizedigital/accessibility-checker/commit/8b1887fce96b2f86d4d0d143976983111808acee) and the revert of that commit [5e47155](https://github.com/equalizedigital/accessibility-checker/commit/5e471554f169da62e0aa450be560ca9dbd9f6757).
