### ISSUE TITLE
Excessive color contrast issues

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#186]
@boonedev can you looks at the 500+ color contrast issues on https://stem.colostate.edu/wp-admin/post.php?post=3419&action=edit

Is this an issue with the plugin?

**Comment by boonedev** [comment]
I think so. The code does a heroic job of processing browser styles through php, but I think the only way to get to an accurate account of what the browser is actually displaying is by using the browser's js. The good news is that the switch to JS should correct the problem.

**Comment by amberhinds** [comment]
OK, awesome. Looking forward to that switch.

**Comment by SteveJonesDev** [comment]
Closing this issue as it will be fixed with JavaScript scanning. https://github.com/equalizedigital/accessibility-checker/issues/246
