### ISSUE TITLE
Incorrect Heading Order flagged when the heading has an ID

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#19]
Incorrect heading order" error appears any time a heading includes an ID (screenshot).

**Comment by amberhinds** [comment]
Sorry, here's the screenshot: https://a.cl.ly/2Nu0D2rp

**Comment by SteveJonesDev** [comment]
Can you provide me with the URL of the page you're having an issue on?

**Comment by amberhinds** [comment]
This one came from Bill.  Based on the headings, I would guess it is
https://cultivatewp.com/privacy-policy/

**Comment by SteveJonesDev** [comment]
This wasn't an issue with the ID attribute. I'm improved the logic to be more accurate. This was pushed as a bug fix to the WordPress repo.
