### ISSUE TITLE
Front End: waiting for issues to load is very slow

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#190]
Is there any way we can improve the performance when you're on the front end and you click the Accessibility Checker button to see issues?

Or if not, cloud it possibly have a loading message so people don't think it's broken?

**Comment by boonedev** [comment]
I've added a "Loading" message and set the cursor to wait while the load is happening - any other changes I should make?

<img width="407" alt="Screenshot 2023-07-05 at 11 16 02 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/ee9d7e4f-b986-45f1-9758-65101c65cea6">


I think the switch to JS should fix as the bulk of the delay is in retrieving the list of warnings from the server, ie: this page takes 2-4 seconds to load everything https://stem.colostate.edu/wbl/?preview=true&_thumbnail_id=3506

**Comment by amberhinds** [comment]
I think this is a good fix until the JS release. Thanks.

*Amber Hinds*
Creative Director & CEO
Road Warrior Creative

***@***.*** • (512) 942-5858 <5129425858> ext. 3
*Connect With Me on LinkedIn <http://bit.ly/AmberLinkedIn> *•
https://roadwarriorcreative.com
