### ISSUE TITLE
Front End: Video not found example

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#191]
<img width="1398" alt="Screen Shot 2023-06-23 at 9 32 42 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/5fec9a51-7916-475c-9f29-fa82f1b23acd">

https://roadwarriorprd.wpengine.com/b-corp/

**Comment by boonedev** [comment]
@amberhinds The switch to JS should fix this.

**Comment by SteveJonesDev** [comment]
The video is found with the current version of the plugin.

<img width="1159" alt="Screenshot 2024-08-01 at 9 15 00 PM" src="https://github.com/user-attachments/assets/f5f1c0c4-3505-4032-bc7e-2ac756910676">
