### ISSUE TITLE
Missing language declaration flagged even though it is present

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#20]
From Bill

On CultivateWP I'm getting "missing language declaration" (https://a.cl.ly/QwubrQBd) but it's there in the source code (https://a.cl.ly/WnulnA8e).

**Comment by SteveJonesDev** [comment]
On CultivateWP when viewing the page source there are more than one <html> tags, which is causing the error. When I inspect the page it's only showing one <html> tag. The others look like they might be part of some caching javascript. The plug gets the HTML without the javascript modifications. I've updated this rule to only check the first <html> tag to prevent this issue.

**Comment by amberhinds** [comment]
Just getting a chance to follow up on this one. I'm not 100% sure that the rule is right here.

On Cultivate I'm seeing these instances of 'lang'

`<html lang="en-US">`
and 
`<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://cultivatewp.com/#organization","name":"CultivateWP","url":"https://cultivatewp.com/","sameAs":[],"logo":{"@type":"ImageObject","@id":"https://cultivatewp.com/#logo","inLanguage":"en-US", [...]`

Is the rule as it's written, seeing the lang in "inLanguage":"en-US" and thinking that is another instance of a language declaration?

If so, that would mean that if the page was missing the actual HTML language declaration, AC would think that a language tag was present and not flag an error? I'm not sure that a screen reader would understand the schema JSON as the language of the page. We would need to test that.

Further, what if the lang attribute is present, but empty?  I don't think we're accounting for that scenario either?

**Comment by SteveJonesDev** [comment]
The issue was there was multiple HTML tags and logging an error on the empty one even though the first one was valid.

It now only checks the first HTML element on the page.

Yes, if there is not an HTML element it doesn't return an error.

> Further, what if the lang attribute is present, but empty? I don't think we're accounting for that scenario either?

Currently it only returns an error if the lang attribute is empty. On line 8 is exits the loop if content is found in the attribute.
`if($elements[0]->getAttribute('lang') != "" || $elements[0]->getAttribute('xml:lang') != "") return;`

**Comment by amberhinds** [comment]
Discussed in team meeting - Bill's site problem is fixed, but this does need to be improved if there is not a lang attribute data all.

**Comment by SteveJonesDev** [comment]
Rule updated to check if the attribute exists and is not empty.
