### ISSUE TITLE
Image Animated GIF doesn't flag on the featured image

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#201]
If an animated GIF is set as the featured image, it's not flagging the warning.

**Comment by boonedev** [comment]
Could you attach the animated gif that isn't being flagged? This one seems to work, so wondering if it's related to the image?
![ezgif-2-eff943509f](https://github.com/equalizedigital/accessibility-checker/assets/695220/4e93fb50-fd01-4db4-bafd-4d4a7574a39c)

<img width="1266" alt="Screenshot 2023-07-06 at 10 28 51 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/43256a43-2302-4c5d-b66b-9408663a9f66">

**Comment by boonedev** [comment]
I've checking for webP animations in case that was the cause.

**Comment by amberhinds** [comment]
I copied the page to https://nasa-gov-preprod.go-vip.net/page-with-featured-image-as-animated-gif/

GitHub says the image is to big to upload.

**Comment by boonedev** [comment]
Images with query string params in their src weren't being evaluated. PR should fix.

**Comment by amberhinds** [comment]
Great, thanks.
