### ISSUE TITLE
Same anchor text pointing to different URLs

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#208]
I'm not sure if this is an enhancement of the "ambiguous link" rule or if we want to add a new issue to flag when when there are links with different hrefs but identical anchors. 

For example this contact links which all email different people but say the same thing.
<img width="668" alt="Screen Shot 2023-07-17 at 3 03 47 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/fc48ab39-b173-400a-b2d8-54fa6ab268f3">

@SteveJonesDev @boonedev do you have an opinion about whether this should be a new rule or part of ambiguous anchor text? 

I'm leaning toward a new rule because we might want to display the other links that flagged on it in some way.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
