### ISSUE TITLE
Ensure frontend highlighting works on frontend pages for all custom post types selected in settings.

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#211]
Currently in the javascript color contrast beta the frontend highlighting panel only shows via the preview link.

**Comment by boonedev** [comment]
[0b17a54](https://github.com/equalizedigital/accessibility-checker/commit/0b17a54228ae516bd4ee20945a9d64b688107d38) should fix

**Comment by SteveJonesDev** [comment]
The panel looks to be showing properly now.
