### ISSUE TITLE
Frontend Highlighting: When enabling styles the element button doesn't show until you scroll.

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#212]
https://github.com/equalizedigital/accessibility-checker/assets/2895788/12aa7f9a-eacc-4a43-a23d-e558e3999be5

**Comment by boonedev** [comment]
@SteveJonesDev I can't replicate but I think this is probably related to https://floating-ui.com/docs/autoUpdate not firing properly. I've enabled a setting that will fire on every animationFrame - could you let me know if that corrects the issue?

**Comment by SteveJonesDev** [comment]
The issue is still there.

https://github.com/equalizedigital/accessibility-checker/assets/2895788/aa3263fa-e4b7-4f6f-99ee-3103314ed38f
