### ISSUE TITLE
Frontend Highlighting: Highlight Button Changes

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#213]
Change the button size to 40 x 40 pixels.
Change position to the top left corner of the element. If that causes too many issues we may need to explore positioning the button below the element.

![Screen Shot 2023-07-27 at 3 42 24 PM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/7becf5bd-c3fe-46c2-920d-325a177a2609)

**Comment by boonedev** [comment]
@SteveJonesDev the floating-ui/dom library I'm using for the buttons allows us to position the button based on the element. I've added this in the latest commit - could you let me know what you think?

```
if(tooltipHeight <= (elHeight * .8) ){
	top = tooltipHeight;
} else {
	top = 0;
}
if( tooltipWidth >= (elWidth * .8) ){
	top = 0;
}

Object.assign(tooltip.style, {
	left: `${x + left }px`,
	top:  `${y + top  }px`
});

```

**Comment by SteveJonesDev** [comment]
This does prevent the button from overlaying on the wrong element. @amberhinds, any thoughts on this positioning?

https://github.com/equalizedigital/accessibility-checker/assets/2895788/e900dc01-2e4f-47fd-864b-33f14ffdb25d

**Comment by SteveJonesDev** [comment]
@boonedev, I did notice this one. Is there any way to account for buttons going off the top or bottom? I guess this is the same issue Amber was having with the buttons going off the sides of the page.

![Screen Shot 2023-07-27 at 11 46 15 PM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/75ff2cd6-7c24-4209-8bfb-fb8d88305ff7)

**Comment by boonedev** [comment]
Good catch. I'll work on it.

**Comment by amberhinds** [comment]
I think what is in the video looks better than it is currently.

**Comment by SteveJonesDev** [comment]
@boonedev, just noting here about the duplicate buttons bug that we were troubleshooting in our meeting on Friday.
<img width="659" alt="Screen Shot 2023-07-30 at 11 59 48 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/e652747f-66c3-48e6-8d66-c796dfe9f9cf">
