### ISSUE TITLE
Change message on post types that cannot be scanned in free

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#232]
Current:
<img width="472" alt="Screen Shot 2023-08-18 at 5 27 02 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/266b1c03-ab63-4e2e-be23-92ad094dfdc8">

Can we get it like this?
<img width="356" alt="Screen Shot 2023-08-18 at 5 27 37 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/ddd6e03d-6abc-4499-9768-fd0170bff443">

**Comment by boonedev** [comment]
All set
