### ISSUE TITLE
Color Contrast converted to javascript rule

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#246]
@boonedev, adding this issue as a placeholder for this feature. Once it's ready for testing please comment here.

**Comment by SteveJonesDev** [comment]
@boonedev, is this ready for testing?

**Comment by boonedev** [comment]
@SteveJonesDev It is

**Comment by SteveJonesDev** [comment]
Status update: The release of this has been delayed for further testing and refinement.

**Comment by amberhinds** [comment]
Thanks for the update.

**Comment by SteveJonesDev** [comment]
Fixed with v1.7.0.
