### ISSUE TITLE
Browser Class

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#255]
This file:
https://github.com/equalizedigital/accessibility-checker/blob/master/includes/classes/browser.php

Is used in the system info file:
https://github.com/equalizedigital/accessibility-checker/blob/master/includes/system-info.php

It is full of WPCS issues (443 ERRORS AND 111 WARNINGS AFFECTING 276 LINES).

This class wasn't created by us. I don't think it's worth our time to fix all the issues. What are your thoughts on this? Is there a better way to get this information? Do we even need this information? Honestly, I've never referenced browser information when troubleshooting people's support inquiries.

**Comment by boonedev** [comment]
@SteveJonesDev The [most recent version](https://github.com/cbschuld/Browser.php) passes phpcs and can be loaded with composer so it was a pretty simple swap out. I've created a PR, but no problem to drop it though if you'd rather.
