### ISSUE TITLE
Divi Incorrect Heading Order

### ISSUE THREAD

**Issue by markaplet** [equalizedigital/accessibility-checker#26]
We see many errors in our Divi pages indicating "Incorrect Heading Order". This error is thrown when we have a sidebar with an heading 2. 

Headings in the main content are not flagged so it appears that it is an issue with special layouts or with content in different columns.

**Comment by markaplet** [comment]
The site is not yet live. I could email you a sample of the page source for inspection if that would be helpful?

**Comment by markaplet** [comment]
I sent you an email Amber.

**Comment by amberhinds** [comment]
Thanks!

**Comment by amberhinds** [comment]
@SteveJonesDev - example HTML code for this is at https://3.basecamp.com/3579237/buckets/16288250/uploads/3406271755

**Comment by SteveJonesDev** [comment]
@amberhinds, I've run that HTML file through the checker and didn't get any heading order errors. We did release improvements to the skipped heading level rule with version 1.0.12.

**Comment by amberhinds** [comment]
@markaplet what version of the plugin were you seeing this error on?

**Comment by markaplet** [comment]
@amberhinds We have Accessibility Checker Version 1.0.12 and Accessibility Checker Pro Version 1.0.0

**Comment by markaplet** [comment]
Side note: Our server admins may have updated the plugins without informing me. so this may have been an issue on a previous version. I do see a notice in the plugin panel that there is an update to the pro version to 1.0.3 Sorry. I wish I was in control of updates. I will try to take a look tomorrow to see if we are still seeing the error reported.

**Comment by SteveJonesDev** [comment]
I believe this issue has been resolved. @markaplet if you still see this issue after updating please let know. Thanks!
