### ISSUE TITLE
Frontend highlighting broken aria reference

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#265]
![Screenshot 2023-09-05 at 5 16 40 PM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/f00fccd4-d171-4f32-9598-8ea340ef4f76)

**Comment by boonedev** [comment]
Before:
<img width="545" alt="Screenshot 2023-09-14 at 11 31 41 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/ee2ba891-b6e6-438c-aa6b-3c701080f727">

After:
<img width="562" alt="Screenshot 2023-09-14 at 11 30 46 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/5255a0e7-a821-4d12-be97-81d7846417b2">
