### ISSUE TITLE
Incorrectly flagged underlined text

### ISSUE THREAD

**Issue by boonedev** [equalizedigital/accessibility-checker#266]
The underlined_text rule can incorrectly parse css and falsely flag content even though it is not underlined. See this page for an example: https://bricks4wp.com/general/replacing-rss-with-wp-api/. 

To prevent the css parsing errors, the rule needs to be ported from php to js.

**Comment by christophermhinds** [comment]
See [11/20/23 Team Meeting Notes - Internal](https://3.basecamp.com/3579237/buckets/1722349/messages/6773425598) for more information / related discussion on this issue.

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

✅ I tested the underline text rule in a couple of different contexts and it appears to correctly flag underlined text with a warning.
