### ISSUE TITLE
I10n functions cannot contain variables

### ISSUE THREAD

**Issue by philwp** [equalizedigital/accessibility-checker#27]
There are multiple files containing `__($variable)` ,  an example of this can be found in [link_ambiguous_text](https://github.com/equalizedigital/accessibility-checker/blob/master/includes/rules/link_ambiguous_text.php#L47), these functions need to be moved to the actual string instead of the variable in order for the plugin to be translated correctly.

**Comment by SteveJonesDev** [comment]
This has been fixed.

https://github.com/equalizedigital/accessibility-checker/commit/114b259ac949f2a63f91d1e96477e3554dc808c6
