### ISSUE TITLE
Reading level update timing bug

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#297]
I thought this was working until I merged it into the master branch and tested it. Sometimes the reading level updates and sometimes it doesn't until you save the post twice. See the screen recording below.

https://www.dropbox.com/scl/fi/nthtzg9wnvpturzpvz0e9/video1587434126.mp4?rlkey=kekh83ebdiyfhj6ddxpd3bupl&dl=0

Create a new PR from the master branch.

**Comment by boonedev** [comment]
Reopening to create a branch based on dev rather than master.
