### ISSUE TITLE
Add check for PHP version.

### ISSUE THREAD

**Issue by philwp** [equalizedigital/accessibility-checker#30]
Plugin will fail when using versions < 7.0  due to spaceship operator https://github.com/equalizedigital/accessibility-checker/blob/master/accessibility-checker.php#L747

We should add a check for PHP version on plugin load.

**Comment by SteveJonesDev** [comment]
The code has been updated to support PHP 5.6 rather than adding a check for PHP version on load. This has been pushed as a bug fix in version 1.1.2.
