### ISSUE TITLE
Undefined variable $record_limit class-scans-stats.php:56

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#303]
<img width="1565" alt="Screenshot 2023-09-14 at 11 08 59 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/b6fa761d-7a4e-4fab-98ed-71d999aebc1e">

Step to reproduce:
1. Go to the Accessibility Check welcome page. /wp-admin/admin.php?page=accessibility_checker

**Comment by boonedev** [comment]
Closed by https://github.com/equalizedigital/accessibility-checker/commit/8af0f00f677ac04473d2b19d79f22ed34a1a7bf8
