### ISSUE TITLE
empty_link.php rule logic false positive

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#304]
Example:
`<a class="twitter social-icon-" href="https://twitter.com/BuildWithWard"><img decoding="async" src="/wp- content/uploads/2023/07/twitter.webp" alt="twitter"/></a>`

Zendesk ticket: 6074

**Comment by boonedev** [comment]
@SteveJonesDev I'm not getting a rule to hit on this when I add it to a page as a custom html block:

`<a class="twitter social-icon-" href="https://twitter.com/BuildWithWard"><img decoding="async" src="/wp-content/uploads/2023/07/twitter.webp" alt="twitter"/></a>`

Any ideas/suggestions?

**Comment by amberhinds** [comment]
I'm seeing this on Highland also for images with alt text.

<img width="1323" alt="Screenshot 2023-09-21 at 3 44 40 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/25e14fdf-4190-4682-aa30-21fe906015a4">

**Comment by amberhinds** [comment]
I'm upgrading this to critical because it's causing huge number of false positives.

**Comment by boonedev** [comment]
@amberhinds Looking into it now.

**Comment by boonedev** [comment]
@amberhinds @SteveJonesDev Here's how I'm reading the rule's logic:

if `<a>` does not have plaintext within the tag &
does have an href &
does not have an aria-label &
does not have a title, it needs to be checked.
	
if `<a>` has an id or name, stop checking. **_(is this correct?)_**
		
if `<a>` doesn't have an id or name and:
The 1st `<img>` inside the `<a>` doesn't have an alt, throw an error.
Or the 1st `<input>` inside the `<a>` doesn't have a value, throw an error.
Or the 1st `<i>` inside the `<a>` doesn't have title and doesn't have aria-label throw an error.
Or the tags inside the `<a>` aren't either img, input, i throw an error. _**(is this correct?)**_
