### ISSUE TITLE
Enable support for WP auto update

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#31]
Since our plugin doesn't output anything on the frontend I think it's a great candidate for WP auto-updates. Can we please make it possible for people to toggle this on if they want it to auto-update (for both free and Pro).

**Comment by SteveJonesDev** [comment]
I believe this is supported natively by WordPress and doesn't require us to update the plugins.

**Comment by amberhinds** [comment]
I just reread core documentation and I think you're right. Never mind!
