### ISSUE TITLE
Settings pages tabs are reversed

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#310]
On all the settings pages the tabs are in reverse order from what they used to be.

/wp-admin/admin.php?page=accessibility_checker_settings
/wp-admin/admin.php?page=accessibility_checker_ignored
/wp-admin/admin.php?page=accessibility_checker_issues

**Comment by boonedev** [comment]
Opened pro issue here: https://github.com/equalizedigital/accessibility-checker-pro/issues/99
