### ISSUE TITLE
Welcome page and dashboard widget last full-site scan date bug

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#319]
![Screenshot 2023-09-20 at 1 29 08 PM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/e6040355-073b-4491-8d25-fa864ab5448e)

Step to replicate:
1. Select posts and pages to scan
2. Run a full site scan
3. After the scan notice last full-site scan date is showing properly
4. Go to settings and uncheck posts from post types to scan and update settings
5. The last full-site scan date is now set to Never on the welcome page

**Comment by SteveJonesDev** [comment]
Let me know if this should be moved to the Pro plugin repo.

**Comment by boonedev** [comment]
Thanks @SteveJonesDev. Correct one! This change
https://github.com/equalizedigital/accessibility-checker/blob/143a3aa40c324d63c536a78a8e807dc3daff7522/includes/classes/class-scans-stats.php#L266
in this pull should fix https://github.com/equalizedigital/accessibility-checker/pull/316
