### ISSUE TITLE
Passed tests should not be able to be negative

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#321]
On the HCC website, the main report is showing -6,229% passed tests.
<img width="715" alt="Screenshot 2023-09-21 at 8 22 24 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/d2d18999-c7cf-4fd1-950e-50a4780e0c77">

They have multiple tests that are not failing:
<img width="826" alt="Screenshot 2023-09-21 at 8 24 51 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/879124b9-0c5c-40c7-8a76-39b1cddf88e3">

So I don't expect this to be zero percent. Event if they were literally failing everything, it would not be negative. The lowest this should go is 0%.

**Comment by SteveJonesDev** [comment]
@amberhinds, I asked about this earlier this week. https://3.basecamp.com/3579237/buckets/29333825/chats/5333625436@6562079669

This is how @boonedev said it's currently calculating.
total rules run = rules x pages tested
total passed rules = total rules run - total failed
% of tests passed = total passed rules / total rules run

I'm not sure this is the correct formula.

**Comment by amberhinds** [comment]
I agree. The number of pages tested is irrelevant to this metric.

We have 42 rules. Based on the screenshot above, this website has passed 14 of them. Therefore, the formula should be:

14 (rules passed) / 42 (total number of rules) * 100 = 33% passed tests.

**Comment by amberhinds** [comment]
Also, I just realized I put this issue in the wrong repo. Sorry.
