### ISSUE TITLE
Update usort() deprecation in future versions of PHP.

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#33]
Deprecated: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /wp-content/plugins/accessibility-checker/partials/settings-page.php on line 16

**Comment by onedraw** [comment]
I'm totally lost. Im getting the same error code 
Deprecated: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/oa9xzzti9d4s/public_html/porngrabbz.com/wp-content/plugins/wp-script-core/wp-script-core.php on line 869
on my website. How do I fix this?

**Comment by amberhinds** [comment]
@onedraw is your site running on PHP v8?

Are you actually seeing functionality problems or are you just seeing the deprecation notice?  We had flagged this as something that we needed to improve in a future version but haven't yet seen any specific problems. If you can provide some additional information that would be helpful.

**Comment by SteveJonesDev** [comment]
Resolved with version 1.2.9
