### ISSUE TITLE
Playground error "Call to undefined function getallheaders"

### ISSUE THREAD

**Issue by boonedev** [equalizedigital/accessibility-checker#332]
<img width="1001" alt="Screenshot 2023-10-05 at 11 11 28 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/695220/1eede092-7b39-4810-a03f-c4fa9146ed22">

**Comment by SteveJonesDev** [comment]
This was fixed with: https://github.com/equalizedigital/accessibility-checker/releases/tag/v1.6.2
