### ISSUE TITLE
URL-specific false positive in the "Link to MS Office" Warning

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#336]
**Request from customer:**

I forgot to share.  I think there is a bug in your checker.

I received this error: "About Link To MS Office File Warnings” with the issue of "Link to MS Office File”.

This is the affected code: 

`<a class="et_pb_button et_pb_button_5 et_pb_bg_layout_light" href="https://www.doc-detroit.com/">Visit Website</a>`

I’m guessing it is seeing the “.doc” in the URL and triggering the error.

**Comment by SteveJonesDev** [comment]
The logic of this rule check has been updated to check for the file extension at the end of the URL. It now disregards URL parameters as well.
