### ISSUE TITLE
Change location of ignore count and make less ambiguous

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#34]
<img width="375" alt="Screen Shot 2021-06-07 at 12 06 31 AM" src="https://user-images.githubusercontent.com/13153456/120961860-38c33780-c724-11eb-8d44-2777c9442c34.png">

I think I've realized that how I had you add the ignore count could be confusing - Also this fails 1.4.1 Use of Color. 🤦‍♀️ 

Let's please move it to the right of the 'i' icon and change it to have the count + ignored items.

So the example above would look like this:
<img width="654" alt="Screen Shot 2021-06-07 at 12 13 17 AM" src="https://user-images.githubusercontent.com/13153456/120962343-2b5a7d00-c725-11eb-9ab4-44674435c4e5.png">

**Comment by SteveJonesDev** [comment]
Ignore labels have been changed and will go out in version 1.3.

![Screen Shot 2022-09-16 at 3 38 07 PM](https://user-images.githubusercontent.com/2895788/190717629-15d41bcd-ba0f-4878-9cd5-824cce099477.png)

**Comment by amberhinds** [comment]
Yay! Thank you!
