### ISSUE TITLE
Underlined Text False Positive

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#344]
<img width="1096" alt="Screenshot 2023-10-19 at 10 20 56 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/52a5e76b-6009-4f16-8e47-b70bf1280776">

These look like false positives because they are targeting links.

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

✅ I tested the underline text rule in a couple of different contexts and it appears to correctly flag underlined text with a warning.
