### ISSUE TITLE
Checking the box to delete all data on uninstall doesn't work

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#347]
I was troubleshooting something on a copy of the TAB website and checked the box to delete all data, saved the settings, then uninstalled and deleted pro, then uninstalled and deleted free.

When I reinstalled them both and went to the settings page, it still had the htaccess credentials saved:
<img width="917" alt="Screenshot 2023-10-23 at 3 18 58 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/83aa7c8a-b475-43af-82ea-b07a72022d22">

**Comment by boonedev** [comment]
Moved to: https://github.com/equalizedigital/accessibility-checker-pro/issues/115
