### ISSUE TITLE
Fix ARIA Hidden casing on post single details tab

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#35]
This is the only one that is not in title case. Please capitalize the H.
<img width="342" alt="Screen Shot 2021-06-07 at 12 24 19 AM" src="https://user-images.githubusercontent.com/13153456/120963164-b4be7f00-c726-11eb-8e67-a3dd4e658a2e.png">

**Comment by SteveJonesDev** [comment]
'learn more' was not in our ambiguous phrases list. It has been added.

https://github.com/equalizedigital/accessibility-checker/commit/497c6c1db3f8c24d6e1efb68b6cc31c5d3cce4dd#diff-993bd92f20bdc72fffb603ffb48d9048da027082c8ea0045961e2e3b8835176dR132

Whitespace is now being trimmed from the beginning and end of the string as well as non-letter characters.

This will go out in the next release.
