### ISSUE TITLE
Readability scan not including the Oxygen meta field

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#36]
Because Oxygen saves page content in a meta field rather than the content field. It's not calculating the readability score for pages built with Oxygen.

A Pro plugin user has requested that we add the Oxygen meta field to our readability scans.

**Comment by SteveJonesDev** [comment]
Oxygen builder shortcode content is now included in the readability scan since version 1.2.4.

97023853beaca10eabc8cdce9b437e3b788bbea0
