### ISSUE TITLE
Change Front End Highlighting to a left or right side panel

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#363]
I'd like us to discuss what it would be like to change Front End highlighting to a panel next to the website rather than a modal over it. I.e., like WAVE or browser dev tools. I think this would be a better user experience and possibly allow for front end scanning?

@SteveJonesDev @boonedev, what do you think about this RE feasibility? What would you need from a design standpoint?

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
