### ISSUE TITLE
Several customers are reporting issues related to our "website is password protected" admin notice

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#373]
There have been a few recent reports that this notice is showing up when it shouldn't (i.e. websites that are not password protected). This appears to be something that happens intermittently.

In one instance, Matt reported the following after resolving the issue:

> For some reason the option that flags the site as requiring a password was set, so I manually removed it. Please let me know if that does not correct the problem.

See:

https://equalizedigital.zendesk.com/agent/tickets/6171
https://equalizedigital.zendesk.com/agent/tickets/6157
https://equalizedigital.zendesk.com/agent/tickets/6133

**Comment by pattonwebz** [comment]
I pushed out a release that will resolve one instance discovered that could falsely trigger this message in [v1.10.0](https://github.com/equalizedigital/accessibility-checker/releases/tag/v1.10.0). Interested to see if more reports of this type come through.

**Comment by pattonwebz** [comment]
https://wordpress.org/support/topic/whoops-it-looks-like-your-website-is-currently-password-protected-2/

**Comment by SteveJonesDev** [comment]
Since a fix has been released for this and we don't have any recent reports of the password message showing falsely I'm closing this out.
