### ISSUE TITLE
Improvements to image empty alternative text and image missing alternative text rules

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#378]
`<img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/? pid=5257932&fmt=gif" />`

This code should be ignored by Image Empty Alternative Text because it has display:none on it.

We may also want to ignore any 1px by 1px images.

**Comment by amberhinds** [comment]
Here's an example of an image that is flagging missing alternative text, but it's got display none and is 0px.
`<img src="//bat.bing.com/action/0?ti=5784293&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" />`

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
