### ISSUE TITLE
Need a setting to move the Accessibility Checker Front End Highlighting open button

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#382]
Many websites have chat and other modals in the bottom right corner. When this happens there's a stacking issue with the Accessibility checker button. Here's just one example:
<img width="955" alt="Screenshot 2023-12-05 at 9 33 27 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/5d3413f4-5de7-4e02-973d-c179584cfee8">

We need a setting for controlling the location of this toggle. It should be a checkbox so people can choose either or both.

Location for Accessibility Checker front-end highlighting button:
- Bottom right corner
- WordPress Admin Bar

Check both by default.

**Comment by SteveJonesDev** [comment]
This was added with [version 1.14.0](https://github.com/equalizedigital/accessibility-checker/releases/tag/v1.14.0).
