### ISSUE TITLE
No need for has_filters checks 

### ISSUE THREAD

**Issue by jdevalk** [equalizedigital/accessibility-checker#388]
There's no reason to check `if has_filters()` before `apply_filters()`. Just do `apply_filters()`. If there are no filters, the function will return the original value. There's no reason to add the extra overhead of `has_filters()`.

**Comment by SteveJonesDev** [comment]
Fixed with https://github.com/equalizedigital/accessibility-checker/pull/414
The same issue has been added to the Pro Plugin.
