### ISSUE TITLE
Bail early

### ISSUE THREAD

**Issue by jdevalk** [equalizedigital/accessibility-checker#391]
Bailing early is a good practice. It makes the code easier to read and understand.

[This thing](https://github.com/equalizedigital/accessibility-checker/blob/master/accessibility-checker.php#L1644-L1650):

```php
if ( $simplified_summary && 'before' === $simplified_summary_position ) {
    return $simplified_summary . $content;
} elseif ( $simplified_summary && 'after' === $simplified_summary_position ) {
    return $content . $simplified_summary;
} else {
    return $content;
}
```
may not be wrong... but why not write it slightly different? The `elseif`/`else` are unnecessary here.

```php
if ( $simplified_summary && 'before' === $simplified_summary_position ) {
    return $simplified_summary . $content;
}
if ( $simplified_summary && 'after' === $simplified_summary_position ) {
    return $content . $simplified_summary;
}
return $content;
```

**Comment by SteveJonesDev** [comment]
Fixed: https://github.com/equalizedigital/accessibility-checker/blob/develop/includes/classes/class-simplified-summary.php#L34-L51
