### ISSUE TITLE
Add an exclusion for wp-spacer-block to the aria-hidden warning

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#40]
This gets a little annoying because it flags it every time the height is different, so it's hard to set a global ignore that works reliably.
<img width="748" alt="multiple WP Spacer Block aria hidden warnings" src="https://user-images.githubusercontent.com/13153456/144135897-16a145d2-4a26-48d8-9c83-e764a6824578.png">

`<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>`

I don't even think these should show as ignored. I think we should just not flag a warning at all when they are present.

**Comment by SteveJonesDev** [comment]
Elements with a class of 'wp-block-spacer' are now being ignored. This will go out in the next release.
