### ISSUE TITLE
Create anchor links in the 'Details' tab for all errors and alerts

### ISSUE THREAD

**Issue by LukaszJaro** [equalizedigital/accessibility-checker#42]
It is sometimes difficult to find out which element on the page is throwing the accessibility issue based on the details view, I can imagine even more difficult for non-tech users to locate it and fix the issue:

Something like webaims panel which upon clicking on the error jumps you to the actual element on the page causing the issue.

![image](https://user-images.githubusercontent.com/10998875/162997491-643524f6-63d8-4d9a-b35d-4d875c3f695b.png)

Or this html validator:
[Nu Html Checker](https://validator.w3.org/nu/)

**Comment by SteveJonesDev** [comment]
The frontend highlighting feature released in version 1.4.0 solves this issue.
