### ISSUE TITLE
Unable to remove password protected login credentials

### ISSUE THREAD

**Issue by LukaszJaro** [equalizedigital/accessibility-checker#43]
I don't even remember who input them there, but I am unable to delete them or I should say once I delete them and try to save, they return as if I didn't delete the credentials.

![image](https://user-images.githubusercontent.com/10998875/163021218-26fa9ba7-5f82-43ae-bc66-61e0547bad94.png)

Running on latest version of the plugin, also attempted to reinstall plugin.
WP Version 5.8.4
PHP 7.4.16

Some more debug info from the plugin itself:

Version:                  1.2.8
Database Version:         1.0.2
Policy Page:              Unset
Activation Date:          2022-04-12 15:09:08
Footer Statement:         Disabled
Authorization Username:   Unset
Authorization Password:   Unset

**Comment by SteveJonesDev** [comment]
It's odd that the Authorization Username and Password show as unset but you're still seeing the Password Protection Login field filled out. Also, I see that the Password field is blue which lead me to speculate if that field is being auto populated.

Do you see any errors in the browser console when on that setting page?

**Comment by LukaszJaro** [comment]
I see no errors in console. But I believe as you mentioned it's something to do with browser auto-fill. In Firefox I tried as well and similar issue occurred. When I checked system info with the credentials saved it displays this:

-- Accessibility Checker Configuration

Version:                  1.2.8
Database Version:         1.0.2
Policy Page:              Unset
Activation Date:          2022-04-12 15:09:08
Footer Statement:         Disabled
Authorization Username:   dvdff
Authorization Password:   nH8AiC4dSCB8wL7ff
Delete Data:              Disabled


However when I deleted the credentials and saved, system info would display the credentials as 'unset' but they would still be visibly filled out on password protected login field.

Just a follow up question, is the passwords supposed to be visible in plain text under system info?

UPDATE: I think this is standard behavior since it also happens on wp-login.php

**Comment by LukaszJaro** [comment]
I think the issue is unintentionally saving users WordPress credentials or some other auto-fill credentials.

Hopefully you can recreate this:

1. Delete the credentials and click save
2. View system info and notice field set to "unset"
3. Go back to general tab, notice auto-fill has credentials filled in
4. Click save
5. View system info

Result: Credentials saved in plain text

Expected: Credentials to be unset

**Comment by SteveJonesDev** [comment]
I believe this is a browser/addon issue. Given there haven't been similar issues, I'm going close this issue out.
