### ISSUE TITLE
Ambiguous Anchor Text rule should ignore punctuation.

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#44]
I came across a link like this:
`<a href="https://website.com/about/"> Learn more.</a>`
which did not flag an ambiguous anchor text error, likely because of the inclusion of the space and the period. 

Can we set this rule to ignore punctuation and leading and trailing spaces?

**Comment by SteveJonesDev** [comment]
'learn more' was not in our ambiguous phrases list. It has been added.

https://github.com/equalizedigital/accessibility-checker/commit/497c6c1db3f8c24d6e1efb68b6cc31c5d3cce4dd#diff-993bd92f20bdc72fffb603ffb48d9048da027082c8ea0045961e2e3b8835176dR132

Whitespace is now being trimmed from the beginning and end of the string as well as non-letter characters.

This will go out in the next release.
