### ISSUE TITLE
Conflict with Yoast SEO and Classic Editor

### ISSUE THREAD

**Issue by boonedev** [equalizedigital/accessibility-checker#450]
See: https://wordpress.org/support/topic/conflict-with-yoast-seo-and-classic-editor/

**Comment by SteveJonesDev** [comment]
@boonedev, we got another support request on this. See the screencast on Ticket #6206. Raise this to a critical issue.

**Comment by SteveJonesDev** [comment]
Fixed with: https://github.com/equalizedigital/accessibility-checker/pull/454
