### ISSUE TITLE
Front End Highlighting Not going to issue on first click.

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#480]
* [X] I've read and understood the [contribution guidelines](https://github.com/equalizedigital/accessibility-checker/blob/develop/.github/CONTRIBUTING.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Clicking buttons in front-end highlighting does not take users to the element on the first click. Thsi seems to be an issues when elements are below the fold, but not always.

Here's a video that shows what I'm talking about: https://app.screencastify.com/v3/watch/cV83iZIsMYOW795N6ia6

I observed it in the beta, but confirmed that the behavior also exists in 1.7.1 and 1.7.0.

Recording was on https://demosite.equalizedigital.com/homemade-turmeric-latte/

Also saw behavior on Highland website (running 1.7.0).

### Please describe what you expected to happen and why.

Clicking the button should work on the first try.

### Dev Notes:
Code: https://github.com/equalizedigital/accessibility-checker/blob/develop/src/frontendHighlighterApp/index.js
Submit a PR to the `develop` branch, and assign @SteveJonesDev reviewer.

**Comment by amberhinds** [comment]
@SteveJonesDev I'm not sure what milestone to add this to.

**Comment by SteveJonesDev** [comment]
@boonedev, to assess by Feb 9th.
