### ISSUE TITLE
Logic on Simplifed Summary Reading level check is off

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#482]
* [X] I've read and understood the [contribution guidelines](https://github.com/equalizedigital/accessibility-checker/blob/develop/.github/CONTRIBUTING.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Simplified Summary Reading Grade Level: 12th
Your simplified summary has a reading level lower than 9th grade.

<img width="484" alt="Screenshot 2024-01-29 at 4 11 28 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/7a4333c4-70da-4acd-9b37-536f40ecbb24">

Also the summary doesn't indicate there's a problem:
<img width="857" alt="Screenshot 2024-01-29 at 4 35 40 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/ac5ba3ab-7e09-458b-99cf-e079eab70cd4">

### Please describe what you expected to happen and why.

If the reading level of the simplified summary if over 9th grade (as in this example) it needs it say that it's over not lower than 9th grade.

On the readability tab, it should not have a checkmark; it should be a red X.

On the Summary Tab, There should be a red X and this sentence: "The reading level of the simplified summary is too high."

### How can we reproduce this behavior?
See: https://demosite.equalizedigital.com/wp-admin/post.php?post=751&action=edit

### Technical info
* WordPress version: 6.4.2
* Accessibility Checker version:

**Comment by SteveJonesDev** [comment]
### Simplified summary grade level over 9th:
<img width="593" alt="Screenshot 2024-02-08 at 12 18 57 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/11ecef06-02ec-45e4-a926-69f3e9a68fa0">
<img width="924" alt="Screenshot 2024-02-08 at 12 19 29 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/b0f9114b-1bc5-44e7-ba63-a1077aec9d94">

### Simplified summary grade level under 9th:
<img width="908" alt="Screenshot 2024-02-08 at 12 22 20 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/f6f0054f-1e35-4560-a942-fc9558c05bf2">
<img width="921" alt="Screenshot 2024-02-08 at 12 22 32 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/eeca4790-8caf-43b4-91c9-3db60a085710">

@amberhinds

**Comment by amberhinds** [comment]
Looks great. Thanks Steve.
