### ISSUE TITLE
Broken Skip or Anchor link with UTF-8 icon in link text; potentially false error

### ISSUE THREAD

**Issue by oldrup** [equalizedigital/accessibility-checker#483]
* [x] I've read and understood the [contribution guidelines](https://github.com/equalizedigital/accessibility-checker/blob/develop/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Accessibility reports a Broken Skip or Anchor link in my Table of Content, when there is a 😉 html-encoded in the link text.
I suspect the check, not to take auto-generated URL-encoded UTF-8 characters into consideration.
A workaround is to enter an ID for the heading manually, without the UTF-8 character.

![image](https://github.com/equalizedigital/accessibility-checker/assets/17141205/b4402260-ebdc-4ce5-ae79-032312a56dd7)
![image](https://github.com/equalizedigital/accessibility-checker/assets/17141205/16424aeb-82d1-4fc5-8735-2ed344d5f71a)

### Please describe what you expected to happen and why.

While using a UTF-8 icon/emoticon in the heading, might be a bad decision for accessibility, I don't think it's technically a "broken link". And the link also works fine on the front end.

### How can we reproduce this behavior?
1. Create a heading with 😉
2. Insert a Simple TOC block 
3. Error is thrown

### Technical info
* WordPress version: 6:4.x
* Accessibility Checker version: 1.7.1

* If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin
- [ ] Page Builder (please specify):

* Which browser is affected (or browsers): 
- [ ] Internet Explorer
- [ ] Edge
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Brave

* Relevant plugins in case of a bug:

https://wordpress.org/plugins/simpletoc/

* Tested with theme:
* Blocksy

**Comment by SteveJonesDev** [comment]
After doing some testing on this it's adding a significant performance hit to the plugin to encode/decode dom elements to account for this use case. I'll leave this open but I'm removing the priority tag.

**Comment by oldrup** [comment]
Okay, thank you, Steve, for looking into this. The issue is minor and totally avoidable. As mentioned, instead of leaving the auto-generated ID as is, I can enter an ID manually, and everything checks out. Also, having a UTF-8 icon encoded character in the ID in the first place, works, but does not really benefit the readability of the link.

I might reach out to the author of the Table Of Contents plugin. Maybe filtering out these emotions from the ID in the first place is more feasible.

Being close to a non-issue with a easy workaround, I'm closing this issue. We can always reopen should it cause headaches to others.

Thank you for your amazing work. Very appreciated.
