### ISSUE TITLE
Make the Link Opens New Window or Tab warning "smarter"

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#49]
Is there any way to add logic to the Link Opens New Window or Tab warning so that it recognizes if people have added a warning and doesn't flag the warning for those links?

[Here is an image of link HTML that might be ignored.](https://my.equalizedigital.com/wp-content/uploads/sites/4/gravity_forms/1-e8ccdbfd3a8bfe1e961f4e12e2d5648a/2022/10/corrected-html.jpg)

Perhaps look for these strings in the <a>:

- opens a new window
- opens a new tab
- opens new window
- opens new tab

**Comment by joedolson** [comment]
Relevant: 

![image](https://user-images.githubusercontent.com/1686451/199331574-6ef99758-c51a-45cb-8975-8b7d18ffe80a.png)

**Comment by amberhinds** [comment]
I actually think we might want to add a new issue for that link. @joedolson is that the optional footer credit link that people can enable?

**Comment by joedolson** [comment]
Yes, it is.

**Comment by SteveJonesDev** [comment]
This rule will now ignore links that contain these phrases.
https://github.com/equalizedigital/accessibility-checker/blob/feature/link-blank-improvements/includes/rules/link_blank.php#L92

checks aria-label
https://github.com/equalizedigital/accessibility-checker/blob/feature/link-blank-improvements/includes/rules/link_blank.php#L21
Example: `<a href="https://equalizedigital.com" target="_blank"  aria-label="Equalize Digital, opens a new window">Equalize Digital</a>`

checks aria-labelledby
https://github.com/equalizedigital/accessibility-checker/blob/feature/link-blank-improvements/includes/rules/link_blank.php#L27
Example: `<div id="mydiv">Equalize Digital, opens a new window</div><a href="https://equalizedigital.com" target="_blank" aria-labelledby="mydiv">Equalize Digital</a>`

checks plain text
https://github.com/equalizedigital/accessibility-checker/blob/feature/link-blank-improvements/includes/rules/link_blank.php#L52
Example: `<a href="https://equalizedigital.com" target="_blank">Equalize Digital, opens a new window</a>`
Example 2: `<a href="https://equalizedigital.com" target="_blank">Equalize Digital, <span class="screen-reader-text">opens a new window</span></a>`

checks image alt
https://github.com/equalizedigital/accessibility-checker/blob/feature/link-blank-improvements/includes/rules/link_blank.php#L58
Example: `<a href="https://equalizedigital.com" target="_blank"><img src="https://equalizedigital.com/image.jpg" alt="Equalize Digital, opens a new window" /></a>`

I've tagged this issue with the documentation tag

**Comment by SteveJonesDev** [comment]
Footer statement link has been updated: `<a href="https://equalizedigital.com/accessibility-checker" target="_blank" aria-label="Accessibility Checker, opens a new window">Accessibility Checker</a>`

**Comment by amberhinds** [comment]
Ooh! Awesome enhancements!

**Comment by amberhinds** [comment]
Documentation updated: https://equalizedigital.com/accessibility-checker/link-opens-new-window-or-tab/
