### ISSUE TITLE
False Positives on Heading Order

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#499]
I'm seeing false positives on the heading order check in multiple different themes. in 1.8.0 +

See https://northwestc1stg.wpenginepowered.com/wp-admin/post.php?post=3651&action=edit#
<img width="1337" alt="Screenshot 2024-02-10 at 6 32 55 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/906c8ea5-faa1-4b52-b70d-9b2de787468d">

**Comment by SteveJonesDev** [comment]
@amberhinds, it's most likely from this: https://github.com/equalizedigital/accessibility-checker/pull/491

I will look into it.

**Comment by SteveJonesDev** [comment]
@amberhinds, this was fixed with the latest v1.8.1 release. The link provided was running v1.8.0. I updated to the latest version and rescanned the page and there are no false positives.

https://github.com/equalizedigital/accessibility-checker/releases/tag/v1.8.1

**Comment by amberhinds** [comment]
OK, thanks for looking. Sorry I missed that issue before.
