### ISSUE TITLE
WordPress fatal error reported while editing post in v1.0.6

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#5]
@SteveJonesDev I received this report from a tester

page where the error was caught: /wp-admin/post.php?post=5190&action=edit&meta-box-loader=1&meta-box-loader-nonce=d4ed55e787&_locale=user

WordPress version 5.6
Current theme: Highwind Child (version 1.1.0)
Current plugin: Accessibility Checker (version 1.0.6)
PHP version 7.3.24-3+ubuntu18.04.1+deb.sury.org+1

Error Details
=============
An error of type E_ERROR was caused in line 11 of the file /nas/content/live/speakinginbyte/wp-content/plugins/accessibility-checker/includes/rules/img_alt_missing.php. Error message: Uncaught Error: Call to a member function find() on bool in /nas/content/live/speakinginbyte/wp-content/plugins/accessibility-checker/includes/rules/img_alt_missing.php:11
Stack trace:
#0 /nas/content/live/speakinginbyte/wp-content/plugins/accessibility-checker/includes/validate.php(96): edac_rule_img_alt_missing(false, Object(WP_Post))
#1 /nas/content/live/speakinginbyte/wp-content/plugins/accessibility-checker/includes/validate.php(50): edac_validate(5190, Object(WP_Post))
#2 /nas/content/live/speakinginbyte/wp-includes/class-wp-hook.php(287): edac_save_post(5190, Object(WP_Post), true)
#3 /nas/content/live/speakinginbyte/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/speakinginbyte/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /nas/content/live/speakinginbyte/wp-includes/post.php(4309): do_action('save_post', 5190, Object(WP_Post), true)
#6 /nas/content/live/speakinginbyte/wp-includes/post.php(4411): wp_insert_post(Array, false, true)
#7 /nas/conten

**Comment by amberhinds** [comment]
Looks like we may need to test for conflicts with https://wordpress.org/plugins/meta-box/. I'll ask Patrick for more info and to post here if he has anything else.  Do you agree that this may be a conflict with that plugin?

**Comment by amberhinds** [comment]
Here's Patrick's plugin list incase that's helpful: https://d.pr/i/ayWTx6

**Comment by SteveJonesDev** [comment]
User confirmed that they are no longer getting the fatal error after updating the plugin.
