### ISSUE TITLE
Activation Issue on old sites - Freemius

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#50]
@SteveJonesDev, Joe Dolson was testing the plugin and discovered this:
"I did discover that your plugin can't be activated on very old sites. Sites created prior to WordPress 2.6 don't have the security tokens in wp-config.php, and Freemius throws fatals if those aren't present. Any site with professional maintenance has probably had the config file upgraded at some point, but it's not done as part of the upgrade process, so it's not a guarantee."

I don't know if this is actually a problem or if there is anything that we need to do so I'm posting here for your review.  Also not sure if this could be related to the support ticket we received this week.

**Comment by SteveJonesDev** [comment]
WordPress 2.6 (Released in 2008) is not a concern as the plugins 'Requires at least' tag is set to 5.0.0. If Freemius requires security tokens I'm not sure there is much we can (or possibly should) do except suggest the user updates there config file.

I will leave this open to do some testing to ensure there isn't something we can do to prevent the fatal error if security tokens are missing.

**Comment by amberhinds** [comment]
I think that what @JoeDolson (not sure if that tag will work) was saying is that if the website was created originally using an old version of WP but is no longer, then the plugin can't be activated. So it might be running the current version of WP but the wp-config will not follow current standards.

I guess the question is how many people are running websites that were created before 2008 and haven't been updated since?  Probably it's a very small number but maybe not?

**Comment by joedolson** [comment]
The wp-config.php would only be updated if a developer has manually gone in and added the necessary constants or if a hosting company auto-updates the config, because wp-config.php is never changed when WordPress is updated.

I suspect there's nothing you can do directly to protect against this other than reporting it upstream to Freemius, and in fact I think that the best resolution for users is just if you can tell them what they need to do to update their wp-config.php files.

**Comment by SteveJonesDev** [comment]
We'll handle this on a case-by-case bases since it's such an edge case. I have submitted a bug report to Freemius to see if there is a more graceful way for Freemius to fail. 

https://github.com/Freemius/wordpress-sdk/issues/589

**Comment by SteveJonesDev** [comment]
Freemius has fixed this and it will be in the next Freemius SDK release.

https://github.com/Freemius/wordpress-sdk/issues/589#issuecomment-1305181839
