### ISSUE TITLE
System Information moved to WordPress Site Health Info

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#502]
Update documentation and support responses to direct users to the built-in WordPress Site Health Info page to copy their site info.

`Admin > Tools > Site Health > Info`

![Screenshot 2024-02-12 at 10 59 37 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/724e647b-3295-4f43-9fc6-ca4449022722)

![Screenshot 2024-02-12 at 10 54 29 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/acc4e0af-8968-43ef-9146-f05ff5528cc1)

**Comment by christophermhinds** [comment]
This is complete.
