### ISSUE TITLE
Improve slashing handling on inputs

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#509]
Seeing this with the usage of input variables `($_GET/$_REQUEST)`, as well as calls to `update_post_meta`.

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

⭕️ I am not sure how to explicitly test this change, or if that's actually possible.

**Comment by pattonwebz** [comment]
@christophermhinds no need to explicitly test this one. If the plugin operates properly then this one works fine :)
