### ISSUE TITLE
Missing headings check add support for role heading

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#52]
Check elements set to a role of heading with an aria-level.

Example: `<div role=heading][aria-level=2]>About Us</div>`

- [x] Dev
- [x] Documentation

**Comment by amberhinds** [comment]
Documentation edited: https://equalizedigital.com/accessibility-checker/missing-headings/#5-how-does-accessibility-checker-test-for-heading-elements
