### ISSUE TITLE
False positives on Duplicate Alt Text

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#522]
* [x] I've read and understood the [contribution guidelines](https://github.com/equalizedigital/accessibility-checker/blob/develop/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

I'm seeing lots of false positives on duplicate alt text, including on images that don't have alt text at all. Here are some examples.

This is on our website - a Facebook pixel icon
<img width="1079" alt="Screenshot 2024-03-06 at 5 16 16 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/946629c1-feec-459f-b9a2-02dc8246a071">

This is on a customer's website - SVG missing alt. (It does also flag Missing Alt errors)
<img width="821" alt="Screenshot 2024-03-06 at 10 36 53 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/1d8521a7-f325-42e4-a8de-1b3157ec5242">

### Please describe what you expected to happen and why.
No false positives. 😜

### How can we reproduce this behavior?
Check the report on https://equalizedigital.com/wp-admin/post.php?post=4991&action=edit

### Technical info
* WordPress version:
* Accessibility Checker version: 1.9.1
* If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [x] Gutenberg
- [ ] Classic Editor plugin
- [x] Page Builder (please specify): Beaver Builder (customer example)

* Tested with theme: Multiple.

**Comment by pattonwebz** [comment]
I have a PR up that resolves the false flagging of duplicate alt text when there was no alt on the images. The problem was expecting an empty string in a strict comparison when the return could be `false` if the attribute didn't exist.

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

🟡 At least in the one test case I'm aware of in the Equalize Digital website footer, it is still flagging that Facebook pixel as having duplicate alternative text after installing the test release and re-scanning the page. See the screenshot below. Looking at it in the front-end highlighting view, it indicates that the element is not visible on the page. I am not sure if that's relevant or not.

<img width="1023" alt="Screenshot 2024-04-30 at 11 17 49 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/25856499/5df49e7e-fb6a-4940-8a8c-3be6c7fcc3a8">
