### ISSUE TITLE
PHPUnit test standardization and updates

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#527]
- Define a standard naming convention for the PHPUnit test. 
- Update the [README](https://github.com/equalizedigital/accessibility-checker/blob/develop/README.md) to include this standard.
- Ensure, running the test locally `npm run test:php` returns the same results as the GitHub workflow.
  - Local seems to currently only run tests with the suffix `Test`
  - Currently local returns: `OK (9 tests, 16 assertions)`
  - Currently, the GitHub workflow returns: `OK (41 tests, 49 assertions)`
- Figure out how to return the test coverage report with our setup and update the [README](https://github.com/equalizedigital/accessibility-checker/blob/develop/README.md) with those instructions

**Comment by pattonwebz** [comment]
This was solved by #542
