### ISSUE TITLE
Tests don't pass if php-intl isn't available in test environment

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#528]
### Please give us a description of what happened.

The `edac_ordinal()` function has code to account for environments that don't have `php-intl` installed. However, the test data doesn't account for it. The function returns the English ordinal for various languages when php-intl is not available.

### Please describe what you expected to happen and why.

Tests for this function cover both situations with and situations without the `php-intl` extension available.

### How can we reproduce this behaviour?
1. Run tests in an env without php-intl
2. See four failing test cases

### Technical info
* WordPress Version: Any
* Accessibility Checker Version: Any

**Comment by pattonwebz** [comment]
I updated the testing setup in #527 so that it now passes when php-intl is not available

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

⭕️ I am unable to test this one as I'm not sure how to set up an environment that's missing the php-intl extension. Sorry!
