### ISSUE TITLE
Add max alt length filter to documentation for the Image Long Alternative Text rule

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#554]
- See pull request: https://github.com/equalizedigital/accessibility-checker/pull/553
- See issue: https://github.com/equalizedigital/accessibility-checker/issues/95
- A new filter has been added called: `edac_max_alt_length`
- The default length is 300 characters

Usage:
```php
function change_max_alt_length() {
    return 100; // New maximum length you want to set.
}
add_filter( 'edac_max_alt_length',  'change_max_alt_length' );
```

**Comment by amberhinds** [comment]
@pattonwebz we don't have an established format for these yet. What do you think of this? https://equalizedigital.com/?p=7709&post_type=a11y-checker&preview=1&_ppp=bf54b5456c

**Comment by pattonwebz** [comment]
The post preview looks good to me. Shows how to use the filter and provides a complete example. This will be more than sufficient for anyone writing code to use for their needs.

**Comment by amberhinds** [comment]
Thanks. Published: https://equalizedigital.com/accessibility-checker/edac_max_alt_length/
