### ISSUE TITLE
Readability of the Quick Start Guide

### ISSUE THREAD

**Issue by joedolson** [equalizedigital/accessibility-checker#56]
Using your own readability check, the quick start guide comes in as a 10th grade reading level. It's fairly verbose, and would benefit from some simplification to try and reach 9th grade or lower. 

The example below reaches the 9th grade marker, but I'm aware that it also makes some changes that could be problematic, e.g. simplifying "post or page" to just "post". It's simpler, but also less accurate, since a) many users do not understand that "post" refers to any post type in WordPress and b) in the free version you don't support every post type. But it's just an example; some of the simplifications many be useful still.

e.g.

Accessibility Checker is here to help you make your website more accessible, whether you're new to website accessibility or a seasoned pro. If you've installed the plugin for the first time, follow these steps to get started:

1. Visit the [Settings Page](https://dev.josephdolson.com/wp-admin/admin.php?page=accessibility_checker_settings) to change settings and set the simplified summary position.

1. Go to the edit screen for the post you want to check; in the free version of Accessibility Checker, scan results are only visible in the post editor.

1. Find the Accessibility Checker section on your edit screen. It is typically found below your content. If you are using a front-end page builder, you will need to visit the back-end edit screen to see Accessibility Checker results.

1. If Accessibility Checkers shows errors or warnings, open the details tab in Accessibility Checker for more information about those issues and how to find them on the page.

1. On the details tab, you can expand each issue to see what that triggered it. If you don't know what an error or warning means, click the "i" icon to visit our documentation. There, you'll find information about the problem and how to fix it.

1. After you have fixed or ignored each open error or warning, update your post to see the accessibility report change. Your goal is to get every page to say 100% Passed Tests.

Watch the video if you would like to see an overview of how to get started with Accessibility Checker.

**Comment by SteveJonesDev** [comment]
The new quickstart guide comes in at a 7th-grade reading level. Closing issue.
https://github.com/equalizedigital/accessibility-checker/blob/master/partials/welcome-page.php#L47C7-L65
