### ISSUE TITLE
Better handling of password protected notice

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#569]
### Please give us a description of what happened.
Currently several different scan issues could result in users seeing the password protected message even if the problem is not the site being password protected.

### Please describe what you expected to happen and why.
Password protected message appears only if the problem is password protection. Users see other notices if the issue is something else. Or a generalised error if we can't determine the issue at the time.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
