### ISSUE TITLE
Refactor EDAC\Admin\Ajax class

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#579]
This [class](https://github.com/equalizedigital/accessibility-checker/blob/develop/admin/class-ajax.php) is very complex (in terms of readability and cognitive complexity) — higher than any other class in the plugin by a long way.

We should consider breaking this up into smaller chunks
1. Moving the large chunks of markup to partials.
2. Check for functionality that can be extracted or reused from elsewhere to prevent duplication.
3. Breaking up the large methods to multiple smaller, testable, ones.

Additionally, it is worth considering whether we can shift a lot of this over to rest endpoints rather than relying on AJAX for all of this.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
