### ISSUE TITLE
Can creation of custom nonce be avoided?

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#580]
There is one place in the validation flow where a shortlived nonce is created via custom methods. We should try to use WordPress nonce creation and validation instead of reimplementing this in the plugin. 

https://github.com/equalizedigital/accessibility-checker/blob/develop/includes/helper-functions.php#L458-L503

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
