### ISSUE TITLE
Oxygen Builder Support

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#59]
With current version of Oxygen Builder the plugin is not generating a readability score. Also, the plugin doesn't seem to be scanning the full page content. It's most likely getting global header and footer elements and not the content area from Oxygen Builder.

**Comment by amberhinds** [comment]
@SteveJonesDev Elijah provided some extra thoughts. I'm opening new issues for each one and closing this one out.

- https://github.com/equalizedigital/accessibility-checker/issues/91
- https://github.com/equalizedigital/accessibility-checker/issues/92
- https://github.com/equalizedigital/accessibility-checker/issues/93
- https://github.com/equalizedigital/accessibility-checker/issues/94

I tagged him on each issue, so you might be able to get additional information from him if needed.
