### ISSUE TITLE
Issues with matching html can't be saved or found via highlighter

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#590]
### Please give us a description of what happened.

If a detected issue has the same html as another issue already found it won't be saved. I encountered this when looking to detect empty paragraphs: `<p></p>` - when the 2nd empty paragraph is found it won't be saved since html is the unique key used for duplicate detection when adding to the database.

Additionally, if you do manage to save these, the highlighter flags only the first instance of it with the additional errors. 

### Please describe what you expected to happen and why.

* Issues are stored when it appears on a different part of the page even if it matches a previously discovered snippet.
* Highlighter can detect _where_ on a page an error is flagged from, even when the html fragment is a duplicate.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
