### ISSUE TITLE
Empty Paragraph Rule Documentation

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#593]
Information can be found on the issue and the PR.
Issue: https://github.com/equalizedigital/accessibility-checker/issues/127
PR: https://github.com/equalizedigital/accessibility-checker/pull/591

**Comment by amberhinds** [comment]
https://equalizedigital.com/accessibility-checker/empty-paragraph-tag/
https://a11ychecker.com/help7870
