### ISSUE TITLE
Missing Transcript False Positives on .avif images

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#598]
<img width="1302" alt="Screenshot 2024-05-01 at 12 51 47 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/8718e2e7-e49a-4702-a360-7087abcf78be">

* Accessibility Checker Version 1.10.2

This is on Dream A World.

**Comment by pattonwebz** [comment]
I haven't looked closely at this, but my initial thought is that we need to not run video rules against these and instead treat `avif` file formats as images - like we treat gifs and web files that can be animated.

**Comment by amberhinds** [comment]
Yeah, I had to google that file format, but it appears to only be used by images not videos.

**Comment by pattonwebz** [comment]
I just looked at this, and the same false positive happens with .avif files being considered as videos, and `video_present` is flagged for them as well.

**Comment by pattonwebz** [comment]
@amberhinds I have a solution for this in PR #695. It will prevent `.avif` being considered for checks that the file format isn't applicable to.

**Comment by amberhinds** [comment]
Thank you!
