### ISSUE TITLE
Text Justified warning is not returning useful HTML

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#6]
On https://demosite.equalizedigital.com/wp-admin/post.php?post=8&action=edit this code is present in an HTML block in the middle of the page:
`<p style="text-align:justify">Lorem ipsum dolor sit amet, conse ctetuer adipiscing elit, sed diam nonummy nibh euismod laoreet.</p>`

There's justified text somewhere else on the page but I'm not sure where.  Accessibility Checker is flagging two warnings but not providing any helpful information.

`text-align: justify (char #: 4518)
text-align:justify (char #: 6849)`

This rule needs to be improved to show the HTML or something identifiable that helps people find what they need to fix.

**Comment by amberhinds** [comment]
Added a documentation label because I need to work on improving this documentation when the bug is fixed.

**Comment by amberhinds** [comment]
In meeting today we discussed rewriting this to be more similar to the small text rule and also checking CSS.

**Comment by SteveJonesDev** [comment]
This rule has been updated to provide informative error code and to check style tags and CSS files. This will go out in the next release.
