### ISSUE TITLE
Review CTA in WP Admin showing up on same day as activation

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#601]
I've seen this on two websites within the same day as activating the plugin:
<img width="1637" alt="Screenshot 2024-05-02 at 3 11 47 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/f11bf7c8-ba40-4f51-8732-a196db260989">

I thought we had a delay before this showed up - did that get messed up during the refactor?

**Comment by SteveJonesDev** [comment]
Yes, there should be a 14-day delay. A bug was likely introduced during refactoring. Possibly here:

<img width="844" alt="Screenshot 2024-05-03 at 12 26 21 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/a19c743a-1d77-443b-857f-a9b04def8760">

**Comment by SteveJonesDev** [comment]
@amberhinds please test this fix:
[accessibility-checker.zip](https://github.com/equalizedigital/accessibility-checker/files/15196573/accessibility-checker.zip)

**Comment by amberhinds** [comment]
@SteveJonesDev I installed this and did not get the notice right away like I was previously.

**Comment by SteveJonesDev** [comment]
Fixed with version [v1.11.1](https://github.com/equalizedigital/accessibility-checker/releases/tag/v1.11.1)
