### ISSUE TITLE
Add Improper Use of Link Rule

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#61]
Documentation for this has been published.
Additional details on our [Tool Tip URL tracker spreadsheet](https://docs.google.com/spreadsheets/d/1KstI--bUZwkccNQpQoFbNtWBPesp3ZlPMaZ9Y9ukpGo/edit?usp=sharing).

Find all of the links on the page that contain only a # in the href attribute or are missing an href attribute completely. If these links do not have role="button" then flag an Improper Use of Link error.

As part of this, # only links should be excluded from flagging a broken skip or anchor link error.

- [x] #63

**Comment by SteveJonesDev** [comment]
@amberhinds, should this rule be called Improper Use of Link or Improper Use of Button? Also, did you create a summary for this rule?

**Comment by amberhinds** [comment]
Improper Use of Link. I named this issue wrong.

**Comment by SteveJonesDev** [comment]
![Image](https://user-images.githubusercontent.com/2895788/202561693-b6fe283c-80b2-4fce-94b2-7e2a2835463f.png)

@amberhinds, should Broken Skip or Anchor Link but updated to allow `<a href="#" role="button">test</a>`?

**Comment by amberhinds** [comment]
<a href="#" role="button">test</a> should flag nothing.

<a href="#">test</a> should flag improper use of link only, not broken skip
or anchor link

**Comment by SteveJonesDev** [comment]
<img width="718" alt="Screen Shot 2022-11-17 at 5 01 05 PM" src="https://user-images.githubusercontent.com/2895788/202569212-e4b1410e-3ea7-44b2-82c2-9c04d3034181.png">

**Comment by amberhinds** [comment]
Yes, that's more what I expected.
