### ISSUE TITLE
Reading Level & Simplified Summary mismatches

### ISSUE THREAD

**Issue by joedolson** [equalizedigital/accessibility-checker#62]
Seeing content show up with inverted logic gates for reading level, e.g.:

![image](https://user-images.githubusercontent.com/1686451/202072772-820d5442-229a-48e6-bad8-c30b6c78004a.png)

and

![image](https://user-images.githubusercontent.com/1686451/202072827-a7243794-c21e-4954-a86b-686584c24249.png)

I expect this is because the value stored in `$summary['readability']` is a string (9th) but the test is a comparison to an integer value at https://github.com/equalizedigital/accessibility-checker/blob/207205abe51e74165f7ffa781a06f9b4ea6f8d31/accessibility-checker.php#L690

- [ ] https://github.com/equalizedigital/accessibility-checker/issues/88

**Comment by SteveJonesDev** [comment]
- [ ] https://github.com/equalizedigital/accessibility-checker/issues/88

**Comment by SteveJonesDev** [comment]
Fixed since version 1.3.21
