### ISSUE TITLE
Welcome screen and widget counts not updating

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#620]
I ran into a situation where the counts are not updating both on the Welcome page and the dashboard widget. Clicking the update counts button doesn't work.
<img width="891" alt="Screenshot 2024-05-13 at 12 09 40 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/417c2f1d-9d61-4d80-83e3-5854ebc9841e">
https://cchadev.wpengine.com/wp-admin/admin.php?page=accessibility_checker

Can you please look into this?

**Comment by pattonwebz** [comment]
This date here is the last time a full site scan was completed (and not the last time any post was scanned). The numbers should update and reflect actual scores on the site, though, and cache for 24 hours. We may want just to:

* update the help text after the block to be more accurate 
* change the label to something like 'last full site scan completed'

**Comment by amberhinds** [comment]
Can the date reflect the time these counts were updated?

That's what I always thought it did.

**Comment by pattonwebz** [comment]
> Can the date reflect the time these counts were updated?

Yeah we can update this date to show the last time the numbers were updated in the widgets.

**Comment by amberhinds** [comment]
Thanks.

**Comment by SteveJonesDev** [comment]
Since this is not actually broken I've reduced the priority. But it would be good to fit this into the next release if possible.

**Comment by pattonwebz** [comment]
@SteveJonesDev I just opened a PR since it was a small change, we can get it in the next release if it gets a code review.
