### ISSUE TITLE
Improper Use of Link Summary

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#63]

**Comment by amberhinds** [comment]
@SteveJonesDev https://equalizedigital.com/accessibility-checker/improper-use-of-link/ Also the summary is on the second tab in this sheet: https://docs.google.com/spreadsheets/d/1KstI--bUZwkccNQpQoFbNtWBPesp3ZlPMaZ9Y9ukpGo/edit?usp=sharing

**Comment by SteveJonesDev** [comment]
Thanks!
