### ISSUE TITLE
Pages with autoplay sound play sounds for 2 seconds during JS scan

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#631]
@bftrick reported that he can hear sound when a page has auto-playing sound during scans in the editor and full site scan.

**Comment by SteveJonesDev** [comment]
The issues wasn't an oembed it was JavaScript errors on the page. We added a timeout to the scan since [Accessibility Checker Pro version 1.8.0](https://github.com/equalizedigital/accessibility-checker-pro/releases/tag/v1.8.0) that allows the scan to continue in this case.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
