### ISSUE TITLE
Oembed that redirects causes scan to fail

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#632]
Seen on XeroShoes a11y site /get-strong. Video in Basecamp and reported by @bftrick.

**Comment by SteveJonesDev** [comment]
The issues wasn't an oembed it was JavaScript errors on the page. We added a timeout to the scan since [Accessibility Checker Pro version 1.8.0](https://github.com/equalizedigital/accessibility-checker-pro/releases/tag/v1.8.0) that allows the scan to continue in this case.
