### ISSUE TITLE
Add an image column that displays images for relevant rules

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#65]
Between "Affected Code" and "Actions"

![Image](https://user-images.githubusercontent.com/2895788/203634937-0cb7ea02-6931-43cd-a11b-b631929ed232.png)

For now this will probably only show on image-related rules, but long term I want to figure out how to screenshot things on the page like axe does.

Should show a thumbnail image that can open in a lightbox when clicked.

**Comment by amberhinds** [comment]
In addition to actual images, this should show SVGs too.

**Comment by SteveJonesDev** [comment]
Added since version 1.3.10
