### ISSUE TITLE
Add a front-end heading tree view

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#654]
I want the plugin to be able to show a heading tree similar to how [HeadingsMap](https://github.com/dzc34/headingsMap) does it on the website's front end.
<img width="176" alt="Screenshot 2024-06-04 at 1 52 55 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/7ea08b53-fc9b-47f0-8bcf-e1b03813b262">

**Comment by SteveJonesDev** [comment]
Move to Basecamp
