### ISSUE TITLE
Filter or setting to define base font size

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#657]
## Is your feature request related to a problem? Please describe.

Some themes have larger base font sizes than the typical 16px which can throw the checks off for certain rules like possible headers or small font.

## Describe the solution you'd like

A filter or setting to tell it what the base font size is to operate with.

## Why do you think this feature is something we should consider for this plugin?

This will provide a useful way to reduce noise in certain themes or websites without affecting those that don't need it.

**Comment by SteveJonesDev** [comment]
@pattonwebz. If we're pulling the computed font size in pixels, isn't the base font size already considered?

**Comment by pattonwebz** [comment]
> @pattonwebz. If we're pulling the computed font size in pixels, isn't the base font size already considered?

It compares font size against exact pixel sizes. 20px is one number we check for possible header. If base font is 16px then 20 is 25% bigger. But if the base size is 18px then the difference to 20 is ~10% bigger only.

**Comment by SteveJonesDev** [comment]
We'd be operating under the assumption it's okay to set the base font size to whatever you want. What if the base font size is set to 100 pixels? Do we not flag a possible heading until 120 pixels? The possible heading is to prevent visual confusion between elements. It may be less about the base font size and more about the element's font size in relation to the heading sizes on the page.

Interesting problem. We may need more input to come to a solution on this.

**Comment by SteveJonesDev** [comment]
Closing out issue. If we need to re-evaluate this a new issue can be opened internally.
