### ISSUE TITLE
Test iThemes Security Compatibility 

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#66]
Test that the plugin scans with this setting turned off.

Security > Settings > Advanced > System Tweaks
Make sure Disable PHP in Plugins is turned off.

**Comment by amberhinds** [comment]
@SteveJonesDev - I got access to a Beaver Builder staging site where I was able to confirm that iThemes Security is blocking the scan. I'll try to test it this week and see if I can isolate a setting.

**Comment by SteveJonesDev** [comment]
Is the setting Disable PHP in Plugins is turned off?

**Comment by amberhinds** [comment]
@SteveJonesDev I had time to retest finally. It is not the Disable PHP in Plugins. It's the "Ban Users" setting under Lockouts (/wp-admin/admin.php?page=itsec&path=%2Fsettings%2Fmodules%2Flockout)

There is a "Default Ban List" setting as a sub item under the Ban Users setting. When the default ban list is enabled, it stops the plugin from scanning.
<img width="690" alt="Default Ban List setting in iThemes Security Pro" src="https://user-images.githubusercontent.com/13153456/209865447-ffe5c37b-c537-42d9-9279-1687d12405ea.png">

This is the explanation for the option: "As a getting-started point you can include the HackRepair.com ban list developed by Jim Walker."

There's no link, however, with some Googling, I think the [default ban list might be this list](https://pastebin.com/BPRv4TDd).

I'm not sure that we can do anything about this, aside from just notifying uses that this setting will block the plugin from being able to scan.

**Comment by SteveJonesDev** [comment]
I'm curious if adding a default user agent to the header of the request might fix this issue. I'll do some testing.

**Comment by SteveJonesDev** [comment]
This was fixed by adding a user_agent for the plugin.
https://github.com/equalizedigital/accessibility-checker/commit/777beb7#diff-760607d970915bf7ff29bded009e0d536ca564b33f09669b59db55860264f49bR204
