### ISSUE TITLE
Add a "Delete and rescan" button in the post edit screen

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#660]
It seems like it would be helpful to have a button that deletes all the post meta and related issues for a single post, then rescans. We're currently doing this by trashing and then restoring posts, which works on staging sites but not on a production site.

Maybe just a "Rescan" button here that deletes everything connected to the post ID and then rescans the post:
<img width="1338" alt="Screenshot 2024-06-05 at 7 01 19 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/411a4d25-6d8c-4c54-859e-0723386e03b4">

It might be good to put the [update dashicon](https://developer.wordpress.org/resource/dashicons/#update) on the button to the left of the text.

**Comment by amberhinds** [comment]
I wonder if we actually want two buttons here - a delete data and a scan button?

There are two reasons why I think this would be helpful. The first is that when troubleshooting scanning issues with @pattonwebz we frequently wanted to clear out the results. The only way to do that currently is to trash the post and then restore it. That works on a staging site, but not on a production site. I think it would be helpful to have a means of clearing the data for any specific post.

The second reason is that updating the post without making any changes is not especially intuitive for users. I think they would be more likely to understand how to trigger a scan if there was a button in the meta box, rather than relying on the post save button.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
