### ISSUE TITLE
Consider using PSR-4 for autoloading and using a more descriptive namespace

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#678]
We should consider how to transition to a more descriptive namespace and while doing that shift over to using a PSR-4 style autoloader.

Suggested namespace that unpacks the acronym to actual names: `EqualizeDigital\AccessibilityChecker`

Possible gains/improvements from transitioning to PSR-4 and new namespace:
* No longer manually managing requires or includes of files.
* Encourage better code and file organisation - if using well defined namespace sub-paths. Currently all class files live inside one large directory with no clear separation, this would be less encouraged if we used PSR-4.
* Interoperability - PSR-4 is widely adopted outside of WP but is also becoming more and more common inside the WP space as well.
* Less decision paralysis because the convention dictates the name of the classes, the filename and the directory they would live in.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
