### ISSUE TITLE
Report that AC wasn't scanning the page unless the panel was right under the content

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#68]
Report received via [dot org support ticket](https://wordpress.org/support/topic/latest-version-1-3-6-problem-with-non-passworded-sites/): 

> Discovered that the Accessibility Checker wasn’t running unless the panel in the Editor was first after the content in the Editor. We had another pane that was coming first (WPCode Lite) that seemed to be preventing A-C running. When these were re-ordered on the page, it ran fine.

Posting this here so we can confirm this is not an issue.

**Comment by SteveJonesDev** [comment]
I've confirmed this isn't an issue. Tested with the same WPCode Lite plugin and the scan worked. It was likely a JavaScript error from another plugin on the customer's website.

<img width="762" alt="Screenshot 2023-09-21 at 9 22 08 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/2895788/0384f836-3143-49dd-94dc-847300ca9816">
