### ISSUE TITLE
Front end highlighting widget does not seem to respect position setting on mobile

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#686]
* [ X] I've read and understood the [contribution guidelines](https://github.com/equalizedigital/accessibility-checker/blob/develop/.github/CONTRIBUTING.md).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

User reported changing the front end highlight widget position setting to "bottom left" does not alter the widget position at mobile screen widths.

### Please describe what you expected to happen and why.

The front-end highlight widget position setting should be respected across mobile, tablet, and desktop screen widths.

### How can we reproduce this behavior?
1. Go to settings and set the highlighting widget to display in the bottom left.
2. Confirm the widget is respecting the position setting at desktop/tablet widths. (It did for me)
3. Then, view a front-end page on the website at mobile widths. The widget will switch back to the default position.

### Technical info
* WordPress version: Latest
* Accessibility Checker version: 1.14.1

**Comment by SteveJonesDev** [comment]
Fixed since version 1.14.2
