### ISSUE TITLE
Pinch-to-Zoom disabled (error)

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#69]
The pinch-to-zoom feature must not be disabled (avoid <meta name="viewport" content="user-scalable=no">). 

When zooming is disabled on a web page, with the parameter user-scalable=no does, low-vision users who use screen magnifiers to read content may be unable to properly see information on a web page.

Maybe part of a whole site scan or on a single page?

Related: https://github.com/equalizedigital/accessibility-checker/issues/589

- [ ] https://github.com/equalizedigital/accessibility-checker/issues/594

**Comment by amberhinds** [comment]
@pattonwebz It looks like the PR for this has already been merged. Here are some changes before we can release it:

1. Change the User-visible title to Zooming and Scaling Disabled (no "is" and use title case) - this will match our other rules.
<img width="355" alt="Screenshot 2024-05-24 at 4 23 43 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/18d203ee-2778-40b0-bb6f-17156c209347">

2. Documentation link should be: /help7947
