### ISSUE TITLE
Empty link rule check misses empty links

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#697]
The `empty_link` check misses empty links. Issue reproduced using this test code `<a href="https://example.com"></a>`.

@pattonwebz is this bug caught when running the end-to-end test in Cypress?

Let's do a patch release on this given its impact.

Ticket: https://wordpress.org/support/topic/cannot-get-empty-link-error-to-trigger/

**Comment by oldrup** [comment]
Looking forward to testing the patch. @SteveJonesDev, what's the preferred channel to get in touch if experiencing potential issues with the free plugin, here on GitHub or the WordPress forums?

**Comment by SteveJonesDev** [comment]
@oldrup either channel is fine.

**Comment by pattonwebz** [comment]
I have a PR up #699 that should fix this and adds some tests to verify that it is working as expected.

@oldrup thanks for reporting this, let me know if you want me to send you a test build to verify this is resolved for you before I release this to the plugin repo.
