### ISSUE TITLE
Fix flaky UrlExists test

### ISSUE THREAD

**Issue by pattonwebz** [equalizedigital/accessibility-checker#711]
There is a test at: /tests/phpunit/helper-functions/UrlExistsTest.php:20

It makes a request to an external site (httpbin) to retrieve an image and check the url exists. The test is flaky though and sometimes the request times out or fails.

Either remove the test; find a different, more reliable, external service; or add a retry logic.

**Comment by SteveJonesDev** [comment]
@pattonwebz, doesn't this PR fix this issue? https://github.com/equalizedigital/accessibility-checker/pull/713

**Comment by pattonwebz** [comment]
@SteveJonesDev yeah I must have not tagged it in the PR summary.

Fixed by: #713
