### ISSUE TITLE
JS error "Uncaught TypeError" possibly related to opt-in modal in Accessibility Checker

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#721]
* [ x] I've read and understood the [contribution guidelines](https://github.com/equalizedigital/accessibility-checker/blob/develop/.github/CONTRIBUTING.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

[See this video](https://share.zight.com/geu7eZPP#discussion) showing user interaction and the error in the user's browser console. 

The error occurred in a local environment, which may make this difficult to replicate. The error appears to be related to our email opt-in modal.

### Please describe what you expected to happen and why.

No JS errors that can be traced to something our plugin is doing.

### How can we reproduce this behavior?

I currently lack information on how to reproduce this error, beyond what's shown in the video.

### Technical info
* WordPress version:
* Accessibility Checker version: Free Version Unknown // Pro Version 1.8.0

* If relevant, which editor is affected (or editors): 

N/A

* Which browser is affected (or browsers): 

Presently this is unknown.

* Relevant plugins in case of a bug:
Uknown plugin stack

* Tested with theme:
Unknown theme

**Comment by pattonwebz** [comment]
I can see why this may happen. The code has a 200ms delay after the page loads before it tries to find the close button and add the focus trap. There may be times where the modal won't appear in 200ms and the code isn't checking before trying to bind.

We can solve this by adding bails if the elements aren't there in time and a retry loop so it attempts to add the focus trap as soon as it's visible.
