### ISSUE TITLE
In some environments SSL cannot be verified so the plugin fails to work

### ISSUE THREAD

**Issue by NicktheGeek** [equalizedigital/accessibility-checker#81]
I was doing some testing with this plugin to see if it could work in our development workflow. To do this I tested locally and found that it failed with an error related to verify the SSL certificate. I followed the error stack and discovered the issue was part of the file_get_html() function in the validate.php file.

This issue would prevent the pro version from working as well even though the public error message indicates it is a problem with the site being password protected, which would be resolved with the pro version, however using a password does not solve the SSL issue.

There is a context that can disable the SSL verification, but due to security it is not a good idea to do that as a blanket solution or via an easy to implement option.

Since this is a local site, there is little risk related to disabling the feature, but it would be much riskier in production and if there is an SSL issue with a prod site, the fix would be to address that issue.

For local use, there should be a way for developers to disable SSL verification. A filter seems to be the most reasonable path forward since it wouldn't be something a client might do on accident.

I create a PR that allows the additional context without breaking the Pro version login.
https://github.com/equalizedigital/accessibility-checker/pull/80

**Comment by SteveJonesDev** [comment]
Thanks, @NicktheGeek I will look into this.

**Comment by SteveJonesDev** [comment]
Added to version 1.3.9
