### ISSUE TITLE
Readability and Simplified Summary Rules Appear Reversed

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#88]
On a customer website, we identified an issue where Accessibility Checker is detecting a 10th Grade reading level, but the "check" indicator on the right hand side reads "Your content has a reading level at or below 9th grade..."

![Screenshot 2022-12-15 142949](https://user-images.githubusercontent.com/25856499/207960645-2c696eb2-72b4-41bb-8238-c7f7299584c8.png)

Video of issue: https://drive.google.com/file/d/1ENEUjP25Jm-x14Zh7aKUrp6Oc6Ju_QcG/view?usp=share_link

NOTE: Video not public. Will be restricted to Equalize Digital employees.

**Comment by SteveJonesDev** [comment]
This is a known issue. https://github.com/equalizedigital/accessibility-checker/issues/62

**Comment by SteveJonesDev** [comment]
@wpxhouston, here is an issue to get started. Notice there are two GitHub issues tracking this bug. Let me know if you have any questions.

**Comment by wpxhouston** [comment]
@christophermhinds Please provide the video access to my google account wpspins.com@gmail.com
