### ISSUE TITLE
Remove or hide the "License" tab from the Free plugin in the WP dashboard

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#89]
This has caused confusion with a couple of customers recently. Amber's recommendation is just to hide this tab entirely so that customers who have already bought the paid version will realize they have to install the software first and not just enter a key to access advanced features.

**Comment by SteveJonesDev** [comment]
If Pro isn't installed there isn't a field to add the key. Wouldn't that be an indicator to install the Pro plugin?

**Comment by SteveJonesDev** [comment]
I don't think this is a bug.

**Comment by SteveJonesDev** [comment]
License tab has been removed from free plugin.
