### ISSUE TITLE
Image missing alternative text does not flag if the same image is added twice on a page

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#9]
I think this should still flag a missing alt error, because, at the least, there should be empty alt tags on the second image.

Example is the macaron image on https://demosite.equalizedigital.com/wp-admin/post.php?post=153&action=edit

**Comment by philwp** [comment]
@amberhinds I'm not sure I understand what you are seeing here.  I see the second macaroon image is showing the Image Missing Alternative Text warning.

<img width="714" alt="Screen Shot 2021-01-06 at 2 16 28 PM" src="https://user-images.githubusercontent.com/5949352/103810855-f210ca80-5029-11eb-83ad-48a42780a71a.png">

**Comment by amberhinds** [comment]
It's been a long time since I looked at this. I see the missing alternative text error that you have in your screenshot but I'm not seeing the instance of the image above in the Image Empty Alternative Text error even though it doesn't have alt text set.

**Comment by SteveJonesDev** [comment]
If it's the same exact image with the same alt text or missing alt text it will only show as one error. Currently the error code is used as the identifier. If it's the same it doesn't save the duplicate. One solution would be to add the line number in the code where the error was found or some incrementing number to the error code to make it unique.

**Comment by amberhinds** [comment]
Per our conversation, this is a known "issue" since we're not adding line numbers to code snippets, but adding those would make it challenging to build out our Fast Track feature for ignores.  Closing for now.
