### ISSUE TITLE
Missing Headings warning doesn't work with Oxygen Builder

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#91]
@Spellhammer provided some extra thoughts and a loom video about this.

Missing headings warning doesn't know about Oxygen's content due to checking $post->post_content instead of $content['html']: [https://www.loom.com/share/d2c843466b474d469c01c2292b36c177](https://www.loom.com/share/d2c843466b474d469c01c2292b36c177)

I think it's worth discussing this rule and whether there is a better way for us to approach this. This issue would also exist on pages built with ACF templated where the subheadings are built into the theme code. But, I'm not certain that changing it to get the entire page's HTML is the answer because I don't want to include sidebars, headers, and footers in this - it's only about getting main content, but given that a ton of themes don't use <main>, I'm not sure how else we do it.

Perhaps there is an option to add in Oxygen's content container to also be checked if Oxygen is active?

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
