### ISSUE TITLE
Oxygen Builder compatibility: edac_oxygen_builder_save_post not working

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#92]
Info from @Spellhammer 

edac_oxygen_builder_save_post not working because it's checking for a specific value in $meta_key but $meta_key has the wrong value for some reason: [https://www.loom.com/share/abf0e285f4754cad8df04c5d92ec68ad](https://www.loom.com/share/abf0e285f4754cad8df04c5d92ec68ad)

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
