### ISSUE TITLE
Oxygen Compatibility: Color Contrast issues not being flagged

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#93]
Color Contrast errors are not being flagged at all in Oxygen, even if the color and background are both set to white on the exact same element.

[Loom video](https://www.loom.com/share/83765f5d3d244e4ea8377ee6cafb13b3) from @Spellhammer

**Comment by SteveJonesDev** [comment]
Closing this issue as it will be fixed with JavaScript scanning. https://github.com/equalizedigital/accessibility-checker/issues/246
