### ISSUE TITLE
Oxygen Compatibility: readability score not working

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#94]
We had a report that with Oxygen Builder, the plugin is not generating a readability score. This is older and needs to be confirmed if this is still an issue.

@Spellhammer, did you see this happening?

**Comment by Spellhammer** [comment]
It does look like there's no readability score when the only content is inside of Oxygen.

To see the issue:
1. Edit a page in Oxygen and add a Rich Text element
2. Add some text inside the Rich Text element
3. Save and return to the WordPress post edit screen for the page
4. See that there's no readability score

These steps may not be sufficient. If there are different steps I should take, I can try those to confirm.

Note for future compatibility: We're probably going to stop using ct_builder_shortcodes at some point in the future, which I can see the readability logic is checking. This logic should be updated to check for both ct_builder_shortcodes **and** ct_builder_json, and use ct_builder_json instead if it's present & populated. 

Please let me know if there's anything else I can do to help with this.

**Comment by Spellhammer** [comment]
I'm not sure if I'm looking in the right function, but in edac_readability_ajax() in accessibility-checker.php, there's a $content variable where Oxygen's content has been included. This all looks correct up to line 1258 and does include the Oxygen content when I output it, but I don't see where this $content variable is actually used, so maybe that's a clue?

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
