### ISSUE TITLE
Add a filter to the images with long alternative text warning so that the max character count can be changed by theme devs

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#95]
Currently this flags at 100 characters and our enterprise client is needs longer alt. If there is a filter that would allow them to change the number of characters taht would be helpful.

In the long run, I want a setting for this in Pro when we build of a settings page for every rule.

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

⭕️ I am unable to test this change as I am unsure how to manually add this filter to a theme file in the appropriate manner. Posting this here as an FYI that it was not tested, incase you want to take another look.
