### ISSUE TITLE
Block site scans from following redirects off-site.

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#96]
This was reported via a [support ticket](https://equalizedigital.zendesk.com/agent/tickets/5808):
Some posts on the blog redirect to an offsite link using custom code and an ACF field. When doing the full site scan, we're seeing issues from other site URLs in the report. Here's a quick screencast to demo: https://drive.google.com/file/d/1qpNHp2Av2bPx6eGRNT0GSBiZBx-b_SxN/view?usp=share_link

I think I also experienced this on BillionToOne's website, which uses the [Page Links To](https://wordpress.org/plugins/page-links-to/) plugin to redirect their blog posts.

We need to code logic into Accessibility Checker scans that stops it from following redirects completely if possible (because you don't want to see issues logged on a post or page that are actually coming from a different post or a page). If that's not possible, can we restrict it from scanning any URLs that are not on the installed domain?

**Comment by SteveJonesDev** [comment]
@wpxhouston, we should probably add a check in the edac_get_content function to compare the found URL with the one defined in WordPress. Possibly using get_home_url.

get_home_url doc:
https://developer.wordpress.org/reference/functions/get_home_url/

Code:
https://github.com/equalizedigital/accessibility-checker/blob/master/includes/validate.php#L232
https://github.com/equalizedigital/accessibility-checker/blob/master/includes/validate.php#L234

**Comment by SteveJonesDev** [comment]
@boonedev, here is the second issue. Please submit a pull request to the master branch. Feel free to ask any questions you may have here.
