### ISSUE TITLE
Front End Highlighting Wrap too big on footer social media icon

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#99]
On https://amberhinds.com/about/ the social media links are empty buttons. The highlighting on this is not especially clear - it would be better if the box was tighter on the icon.

<img width="1788" alt="highlight goes full-width" src="https://user-images.githubusercontent.com/13153456/217906982-5bb376b0-0dd2-400f-9bc1-bea4329fb0da.png">

code snippet being flagged:
`<a href="https://www.facebook.com/aucoeurblog" target="_blank"><i class="fab fa-facebook-f"></i></a>`

**Comment by SteveJonesDev** [comment]
This is fixed with the most updated highlight code.

![Screen Shot 2023-04-07 at 2 50 41 PM](https://user-images.githubusercontent.com/2895788/230661886-234931b8-8c4e-489d-a397-c470fe128531.png)
